import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';import {createHelpuServer} from '../server.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-admin-visual-')),output=path.resolve('../output/admin-area');fs.mkdirSync(output,{recursive:true});let browser;const env={};
const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,whatsappChatEnv:{}}});await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;
try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});const errors=[];
 async function account(name){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const r=await context.request.post(origin+'/api/auth/signup',{headers:{Origin:origin},data:{name,email:name+'@example.test',password:'only-test-12345',company:name}});assert.equal(r.status(),201);const boot=await(await context.request.get(origin+'/api/portal/bootstrap')).json();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {context,page,boot};}
 const op=await account('Equipe'),customer=await account('Cliente');env.HELPU_OPERATOR_USER_IDS=String(op.boot.user.id);const p=op.page;
 await p.goto(origin+'/portal.html');await p.waitForURL('**/admin.html');await p.getByRole('heading',{name:'Sua operação, em um só lugar.'}).waitFor();assert.equal(await p.locator('#onboarding').count(),0);assert.equal(await p.getByRole('link',{name:'Conversa',exact:true}).count(),0);
 async function shot(name){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name);await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
 await shot('inicio-desktop');for(const width of [390,320]){await p.setViewportSize({width,height:1000});await shot('inicio-'+width);}await p.setViewportSize({width:1440,height:1000});
 await p.getByRole('link',{name:'Clientes',exact:true}).click();await p.getByRole('heading',{name:'Clientes da Helpu.'}).waitFor();await p.getByRole('searchbox',{name:'Buscar empresa'}).fill('Cliente');assert.equal(await p.locator('[data-client-name]:visible').count(),1);await shot('clientes');
 for(const [label,title] of [['Publicações','Fila da equipe'],['Consultorias','Consultorias da equipe'],['Comercial','Apresentações e conversas.'],['Planos e custos','Planos com entrega e margem.']]){await p.getByRole('link',{name:label,exact:true}).click();await p.getByRole('heading',{name:title,exact:true}).waitFor();assert.equal(await p.getByText('Acesso restrito à equipe autorizada.',{exact:true}).count(),0);}
 await p.getByRole('button',{name:'Estruturar oferta',exact:true}).click();await p.locator('[name=name]').fill('Rascunho no admin');await p.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await p.getByRole('button',{name:'Editar ficha',exact:true}).waitFor();await p.getByRole('button',{name:'Fechar',exact:true}).click();await shot('planos');
 await p.getByRole('link',{name:'Abrir minha empresa ↗',exact:true}).click();await p.waitForURL('**/portal.html?mode=client#/company');await p.getByRole('heading',{name:'Seu negócio. Sua direção.'}).waitFor();assert.equal(await p.getByRole('link',{name:'Operação Helpu',exact:true}).count(),0);await p.getByRole('link',{name:'Administração',exact:true}).click();await p.waitForURL('**/admin.html');
 await customer.page.goto(origin+'/admin.html');await customer.page.getByRole('heading',{name:'Acesso restrito à equipe Helpu'}).waitFor();assert.equal(await customer.page.locator('#admin-shell').isVisible(),false);assert.equal((await customer.context.request.get(origin+'/api/portal/admin-overview')).status(),403);await customer.page.getByRole('link',{name:'Abrir meu portal'}).click();await customer.page.getByRole('heading',{name:'O que vamos fazer pela sua marca?'}).waitFor();
 await p.goto(origin+'/portal.html#/admin');await p.waitForURL('**/admin.html#/admin');await p.getByRole('heading',{name:'Fila da equipe'}).waitFor();assert.deepEqual(errors,[]);assert.equal((await app.database.prepare('SELECT COUNT(*) AS n FROM jobs').get()).n,0);console.log(JSON.stringify({ok:true,output,checks:['admin landing redirect','separate navigation','client directory','all four reused modules','draft persistence','explicit client portal return','client denied','legacy links redirect','1440/390/320 px']}));
}finally{await browser?.close();await app.portal.shutdown();await new Promise(r=>app.close(r));const target=path.resolve(dir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-admin-visual-'));fs.rmSync(target,{recursive:true,force:true});}
