import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';import {createDatabase,bindDatabaseScope} from '../portal/database.mjs';
import {createAIManagement} from '../portal/ai-management.mjs';import {aiModel,aiRequest} from '../portal/ai-routing.mjs';import {estimateTextCost,estimateImageCost} from '../portal/ai-costs.mjs';import {EVAL_CASES,gradeEvaluation,evaluationRequest,runEvaluation} from '../portal/ai-evals.mjs';import {recordProviderUsage} from '../portal/provider-usage.mjs';
const now=Date.parse('2026-09-20T15:00:00Z');
test('roteamento preserva escolhas existentes, separa tarefas e não promove modelo em erro',()=>{
 const c={agentModel:'saved-expensive',model:'small-structured',aiRouting:{routes:{conversation:'gpt-5.6-sol'}}};assert.equal(aiModel(c,'conversation'),'gpt-5.6-sol');assert.equal(aiModel(c,'agent'),'small-structured');assert.equal(aiModel(c,'creation_plan'),'saved-expensive');assert.equal(aiModel({...c,aiRouting:{routes:{conversation:'invalid'}}},'conversation'),'saved-expensive');assert.deepEqual(aiRequest(c,'conversation'),{model:'gpt-5.6-sol',service_tier:'default'});
});
test('imagem exige divisão de tokens e não inventa desconto de cache misto',()=>{
 const b={model:'gpt-image-2.5-sunburst',observedAt:now,serviceTier:'default',tokens:{input:1000,textInput:100,imageInput:900,cachedInput:0,output:500}};
 assert.equal(estimateImageCost(b).usd,.0227);assert.equal(estimateImageCost({...b,tokens:{...b.tokens,cachedInput:10}}).usd,null);assert.equal(estimateImageCost({...b,tokens:{...b.tokens,textInput:null}}).usd,null);
});
test('avaliação permite consultas simuladas e encerra após três passos',async()=>{
 let calls=0;const c=EVAL_CASES[0];const r=await runEvaluation('gpt-5.6-sol',c,async body=>{calls++;if(calls===1)return {status:'completed',output:[{type:'function_call',name:'operation_status',call_id:'probe',arguments:'{}'}]};assert.ok(body.input.some(x=>x.type==='function_call_output'));return response(c,'gpt-5.6-sol','done');});assert.equal(r.grade.passed,true);assert.equal(calls,2);
 calls=0;const loop=await runEvaluation('gpt-6-astra',c,async()=>{calls++;return {status:'completed',output:[{type:'function_call',name:'operation_status',call_id:'probe-'+calls,arguments:'{}'}]};});assert.equal(calls,3);assert.equal(loop.grade.passed,false);
});
test('preços não duplicam cache/raciocínio e custos desconhecidos nunca viram zero',()=>{
 const base={model:'gpt-5.6-sol',tokens:{input:1000,cachedInput:500,output:100,reasoningOutput:90},operation:'conversation',observedAt:now,serviceTier:'default'};
 assert.equal(estimateTextCost(base).usd,.0042);assert.equal(estimateTextCost({...base,model:'gpt-6-astra'}).usd,.0105);
 for(const change of [{model:'unknown'},{tokens:{input:100,output:10}},{operation:'image'},{serviceTier:'priority'},{observedAt:Date.parse('2026-01-01')},{observedAt:Date.parse('2027-01-01')},{tokens:{input:100,cachedInput:101,output:0}},{tokens:{input:100,cachedInput:0,output:0,cacheWriteInput:100}}])assert.equal(estimateTextCost({...base,...change}).usd,null);
 assert.equal(estimateTextCost({...base,tokens:{input:300000,cachedInput:100000,output:1000}}).usd,1.71);
});
function response(c,model,id){const e=c.expected,args={format:e.format||'reels',duration:e.duration||15,attachments:[...(e.attachments||['foto-a']),...(e.reference||[])],videoOptions:{musicAssetId:e.music||null},referenceOnlyIds:e.reference||[]};return {id,model,status:'completed',service_tier:'default',usage:{input_tokens:1000,input_tokens_details:{cached_tokens:500},output_tokens:100},output:e.status?[{type:'function_call',name:'operation_status',arguments:'{}'}]:e.noCreate?[{type:'message',content:[{type:'output_text',text:e.question?'Qual marca deseja divulgar?':'Referência recebida.'}]}]:[{type:'function_call',name:'create_media',arguments:JSON.stringify(args)}]};}
test('casos com ferramentas reais detectam perda de contexto sem executar ferramentas',()=>{for(const c of EVAL_CASES){const b=evaluationRequest('gpt-5.6-sol',c);assert.ok(b.tools.some(t=>t.name==='create_media'));assert.equal(b.max_output_tokens,2000);assert.equal(gradeEvaluation(response(c,'gpt-5.6-sol','test'),c).passed,true);}assert.equal(gradeEvaluation({status:'completed',output:[]},EVAL_CASES[0]).passed,false);});
for(const postgres of [false,true])test('gestão privada, comparação, aceite, histórico e reversão '+(postgres?'PostgreSQL':'SQLite'),async()=>{
 let pg,db;if(postgres){pg=await PGlite.create({parsers:{20:Number}});await pg.exec('CREATE SCHEMA helpu');db=createDatabase({pool:{async connect(){return {async query(sql,args){const r=await pg.query(sql,args);return {...r,rowCount:r.affectedRows};},release(){}};},async end(){}}});}else db=createDatabase({filename:':memory:'});
 try{for(const sql of ('CREATE TABLE '+(postgres?'helpu.':'')+'companies(id TEXT PRIMARY KEY,name TEXT); CREATE TABLE '+(postgres?'helpu.':'')+'records(id TEXT PRIMARY KEY,org_id TEXT,kind TEXT,data TEXT,external_id TEXT,created_at BIGINT,updated_at BIGINT,version INTEGER DEFAULT 1,UNIQUE(org_id,kind,external_id)); CREATE TABLE '+(postgres?'helpu.':'')+'jobs(id TEXT,org_id TEXT,kind TEXT,state TEXT,payload TEXT,attempts INTEGER,created_at BIGINT);').split(';').filter(s=>s.trim()))await db.exec(sql);await db.prepare('INSERT INTO companies VALUES(?,?)').run('a','Empresa A');await db.prepare('INSERT INTO companies VALUES(?,?)').run('b','Empresa B');
 let calls=0,failNext=false;const user={id:1},m=bindDatabaseScope(db,createAIManagement({db,operator:u=>u.id===1,now:()=>now,integration:async()=>({apiKey:'never-expose',agentModel:'gpt-6-astra',model:'gpt-5-mini'}),respond:async(_,body)=>{calls++;if(failNext)throw Error('private failure');const c=EVAL_CASES.find(c=>body.input.at(-1).content===c.messages.at(-1));return response(c,body.model,'response_'+calls);}}));
 await assert.rejects(m.listing('a',{id:2}),e=>e.status===403);assert.equal((await m.listing('a',user)).effective.agent,'gpt-5-mini');
 const batch=randomUUID();for(const c of EVAL_CASES)for(const model of ['gpt-5.6-sol','gpt-6-astra']){const d={action:'evaluate',batch,caseId:c.id,model,confirmed:true};assert.equal((await m.action('a',user,d)).passed,true);await m.action('a',user,d);}assert.equal(calls,16);
 let l=await m.listing('a',user);assert.equal(l.report.calls,16);assert.equal(l.report.priced,16);assert.ok(l.report.knownUsd>0);assert.equal((await m.listing('b',user)).report.calls,0);assert.ok(!JSON.stringify(l).includes('never-expose'));
 const change={action:'save',routes:{conversation:'gpt-5.6-sol'},version:0,reason:'Avaliação dos casos e qualidade revisadas',qualityReviewed:true,batch};await assert.rejects(m.action('a',user,{...change,qualityReviewed:false}));await assert.rejects(m.action('b',user,change));await assert.rejects(m.action('a',user,{...change,routes:{agent:'invalid'}}));
 const p=await m.action('a',user,change);assert.equal(p.routes.conversation,'gpt-5.6-sol');assert.equal(p.routes.agent,undefined);await assert.rejects(m.action('a',user,change));
 l=await m.listing('a',user);assert.equal(l.history.length,1);const restored=await m.action('a',user,{action:'rollback',historyId:l.history[0].id,version:p.version,reason:'Reverter para conferir qualidade'});assert.deepEqual(restored.routes,{});
 failNext=true;const failed={action:'evaluate',batch:randomUUID(),caseId:'duration',model:'gpt-5.6-sol',confirmed:true};assert.equal((await m.action('a',user,failed)).state,'uncertain');await m.action('a',user,failed);assert.equal(calls,17);assert.ok(!JSON.stringify(await m.listing('a',user)).includes('private failure'));
 await recordProviderUsage(db,{org_id:'a',id:'unknown-job'},{id:'unpriced',model:'image-model'},{operation:'image',observedAt:now});assert.equal((await m.listing('a',user)).report.unpriced,1);
 }finally{await db.close();await pg?.close();}
});
