import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createHelpuServer} from '../server.mjs';import {testPng} from './image-fixture.mjs';
test('roteamento administrativo alcança chat e plano de mídia; chave e controles ficam privados',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-ai-routing-')),env={},models=[];const usage={input_tokens:1000,input_tokens_details:{cached_tokens:0},output_tokens:100};
 const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,openaiEnv:{OPENAI_API_KEY:'routing-test-key',OPENAI_MODEL:'gpt-6-astra'},conversationRespond:async(_,body)=>{models.push(body.model);return {id:'route-chat',model:body.model,status:'completed',usage,output:[{type:'message',content:[{type:'output_text',text:'Posso ajudar com o conteúdo.'}]}]};},creationRespond:async(_,body)=>{models.push(body.model);return {id:'route-plan',model:body.model,status:'completed',usage,output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({caption:'Confira a novidade.',slides:[{title:'Novidade',text:'Conheça',visualPrompt:'Fundo branco e verde',background:'#ffffff',textColor:'#002200'}]})}]}]};},providers:{generateImage:async(_,{size})=>({base64:testPng(...size.split('x').map(Number)).toString('base64')})}}});
 await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;let cookie;
 const req=async(route,body)=>{const r=await fetch(origin+route,{method:body?'POST':'GET',headers:{Cookie:cookie||'',Origin:origin,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});cookie=r.headers.get('set-cookie')?.split(';')[0]||cookie;return {status:r.status,body:await r.json()};};
 try{await req('/api/auth/signup',{name:'Teste',company:'Marca',email:'routing@example.test',password:'test-password-long'});const boot=(await req('/api/portal/bootstrap')).body,org=boot.companies[0].id,prefix='/api/portal/'+org;
  assert.equal((await req('/api/portal/ai-management?org='+org)).status,403);env.HELPU_OPERATOR_USER_IDS=String(boot.user.id);
  await app.database.prepare("INSERT INTO records(id,org_id,kind,data,created_at,updated_at) VALUES(?,?,'ai_routing',?,?,?)").run('ai-routing:'+org,org,JSON.stringify({routes:{conversation:'gpt-5.6-sol',creation_plan:'gpt-5.6-sol'}}),Date.now(),Date.now());
  const status=await req('/api/portal/ai-management?org='+org);assert.equal(status.status,200);assert.equal(status.body.effective.agent,'gpt-5-mini');assert.ok(!JSON.stringify(status.body).includes('routing-test-key'));
  const t=(await req(prefix+'/conversations',{title:'Teste'})).body;assert.equal((await req(prefix+'/conversations/'+t.id+'/messages',{text:'Olá, preciso de ajuda.',mode:'plan'})).status,201);await app.portal.tick();
  assert.equal((await req(prefix+'/creations',{requestId:'routing-image-test',format:'feed',prompt:'Crie uma arte verde.',attachments:[]})).status,201);await app.portal.tick();assert.deepEqual(models,['gpt-5.6-sol','gpt-5.6-sol']);
  const ledger=(await app.database.prepare("SELECT data FROM records WHERE org_id=? AND kind='provider_usage'").all(org)).map(r=>JSON.parse(r.data));assert.equal(ledger.filter(r=>['conversation','creation_plan'].includes(r.operation)&&r.model==='gpt-5.6-sol').length,2);assert.ok(ledger.filter(r=>r.model==='gpt-5.6-sol').every(r=>r.latencyMs>=0&&r.estimatedCost.usd>0));
 }finally{await app.portal.shutdown();await new Promise(r=>app.close(r));assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-ai-routing-'));fs.rmSync(dir,{recursive:true,force:true});}
});
