import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright-core';
import {createHelpuServer} from '../server.mjs';
import {testPng} from './image-fixture.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-assisted-visual-')),output=path.resolve('../output/f07');fs.mkdirSync(output,{recursive:true});
let time=Date.now(),browser;const env={};
const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,assistedNow:()=>time,whatsappChatEnv:{}}});await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;
try{
  browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});
  async function account(name){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',timezoneId:'America/Sao_Paulo'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const res=await context.request.post(origin+'/api/auth/signup',{headers:{Origin:origin},data:{name,email:name.replaceAll(' ','').toLowerCase()+'@example.test',password:'only-test-12345',company:name}});assert.equal(res.status(),201);const boot=await(await context.request.get(origin+'/api/portal/bootstrap')).json();await context.request.post(origin+'/api/portal/'+boot.companies[0].id+'/onboarding',{headers:{Origin:origin},data:{action:'skip'}});const page=await context.newPage();return {page,context,boot};}
  const client=await account('Cliente Visual'),operator=await account('Operador Visual');env.HELPU_OPERATOR_USER_IDS=String(operator.boot.user.id);
  const errors=[];for(const x of [client,operator])x.page.on('pageerror',e=>errors.push(e.message));
  const org=client.boot.companies[0].id,asset=randomUUID(),bytes=testPng();fs.writeFileSync(path.join(dir,'uploads',asset+'.png'),bytes);await app.database.prepare('INSERT INTO assets(id,org_id,name,mime,size,path,source_url,created_at) VALUES(?,?,?,?,?,?,?,?)').run(asset,org,'Foto do imóvel','image/png',bytes.length,asset+'.png',null,time);
  const p=client.page,o=operator.page;
  const local=n=>{const d=new Date(n);return new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d).replace(' ','T');};
  const submit=async(page,action)=>{const f=page.locator('[data-assisted-form="'+action+'"]');await f.locator('button').click();await f.waitFor({state:'hidden'});};
  const shot=async(page,name)=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name);await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});};
  await p.goto(origin+'/portal.html#/assisted');await p.getByLabel('Usuário do Instagram',{exact:true}).fill('cliente_imoveis');assert.equal(await p.locator('[name=consent]').isChecked(),false);await p.locator('[name=consent]').check();await submit(p,'authorize');
  await p.getByRole('button',{name:'Solicitar publicação',exact:true}).click();await p.getByLabel('Título do pedido').fill('Imóvel em destaque');await p.getByLabel('Foto do imóvel',{exact:true}).check();await p.getByLabel('Legenda final').fill('Agende sua visita.');await p.getByLabel('Data e horário desejados (horário deste dispositivo)').fill(local(time+3600000));await p.getByText('Solicitar impulsionamento (opcional)',{exact:true}).click();await p.locator('[name=boostRequested]').check();await p.getByLabel('Intenção de verba de mídia').selectOption('5000');await p.getByLabel('Objetivo do anúncio').fill('Visitas ao perfil');await p.getByLabel('Cidade e público').fill('Vacaria, interessados em imóveis');await p.getByLabel('Início desejado',{exact:true}).fill(local(time+7200000));await p.getByLabel('Fim desejado',{exact:true}).fill(local(time+86400000));await submit(p,'create');await p.getByRole('heading',{name:'Imóvel em destaque',exact:true}).waitFor();await shot(p,'cliente-desktop');
  await o.goto(origin+'/portal.html#/admin');await o.getByRole('button',{name:'Abrir pedido',exact:true}).waitFor();await o.getByText(/Clientes e acessos delegados/).click();await o.getByRole('button',{name:'Conferir acesso delegado'}).click();await o.getByLabel('Como o acesso foi conferido').fill('Permissão de publicação conferida na Meta para cliente_imoveis.');await submit(o,'verify_access');
  await o.getByRole('button',{name:'Abrir pedido',exact:true}).click();await o.getByRole('button',{name:'Enviar versão para aprovação'}).click();await submit(o,'submit_review');
  await o.getByRole('button',{name:'Abrir pedido',exact:true}).click();await o.getByRole('button',{name:'Validar / rever orçamento'}).click();await o.getByLabel('Taxa Helpu separada (R$)').fill('0');await submit(o,'quote');await shot(o,'admin-desktop');
  await p.getByRole('button',{name:'Atualizar fila'}).click();await p.getByRole('button',{name:'Abrir pedido',exact:true}).click();await p.setViewportSize({width:390,height:1000});await shot(p,'aprovacao-celular');assert.equal(await p.locator('[data-assisted-form=approve] [name=consent]').isChecked(),false);await p.locator('[data-assisted-form=approve] [name=consent]').check();await submit(p,'approve');
  await p.getByRole('button',{name:'Abrir pedido',exact:true}).click();await p.locator('[data-assisted-form=boost_approve] [name=consent]').check();await submit(p,'boost_approve');
  time+=3601000;await o.getByRole('button',{name:'Atualizar fila'}).click();await o.getByRole('button',{name:'Abrir pedido',exact:true}).click();await o.getByRole('button',{name:'Iniciar publicação manual'}).click();await submit(o,'start_publication');await o.getByRole('button',{name:'Abrir pedido',exact:true}).click();await o.getByRole('button',{name:'Registrar link publicado'}).click();await o.getByLabel('Link da publicação no Instagram').fill('https://www.instagram.com/p/f07-test/');await submit(o,'published');
  await p.getByRole('button',{name:'Atualizar fila'}).click();await p.setViewportSize({width:320,height:1000});await shot(p,'cliente-320');await p.getByRole('button',{name:'Abrir pedido',exact:true}).click();await p.getByRole('link',{name:'Ver publicação registrada ↗'}).waitFor();assert.equal(await p.locator('#editor').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);await shot(p,'publicado-320');
  await o.setViewportSize({width:320,height:1000});await shot(o,'admin-320');
  assert.deepEqual(errors,[]);assert.equal((await app.database.prepare('SELECT COUNT(*) AS count FROM jobs').get()).count,0);console.log(JSON.stringify({ok:true,output,checks:['Autorização explícita','Pedido com mídia e verba','Acesso delegado registrado','Aprovação separada de peça e orçamento','Operador registra publicação manual','Desktop e 320/390 px','Nenhuma publicação, mensagem, cobrança ou IA real']}));
}finally{await browser?.close();await app.portal.shutdown();await new Promise(r=>app.close(r));const target=path.resolve(dir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-assisted-visual-'));fs.rmSync(target,{recursive:true,force:true});}
