import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {createHelpuServer} from '../server.mjs';
import {OFFER_FIELDS} from '../dist/assets/commercial-schema.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-commercial-visual-')),output=path.resolve('../output/f09');fs.mkdirSync(output,{recursive:true});let browser;const env={};
const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,whatsappChatEnv:{}}});await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;
try{
  browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});
  const errors=[],failed=[];async function context(){const c=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',timezoneId:'America/Sao_Paulo'});await c.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());c.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url()+' '+r.status());});});return c;}
  async function account(name){const c=await context(),email=name.replaceAll(' ','').toLowerCase()+'@example.test';const res=await c.request.post(origin+'/api/auth/signup',{headers:{Origin:origin},data:{name,email,password:'only-test-12345',company:name}});assert.equal(res.status(),201);const boot=await(await c.request.get(origin+'/api/portal/bootstrap')).json();await c.request.post(origin+'/api/portal/'+boot.companies[0].id+'/onboarding',{headers:{Origin:origin},data:{action:'skip'}});return {context:c,page:await c.newPage(),boot,email};}
  const op=await account('Equipe Comercial'),customer=await account('Cliente Comercial'),visitor=await context(),p=await visitor.newPage(),o=op.page,c=customer.page;env.HELPU_OPERATOR_USER_IDS=String(op.boot.user.id);
  const upload=await op.context.request.post(origin+'/api/portal/'+op.boot.companies[0].id+'/files',{headers:{Origin:origin,'Content-Type':'image/webp','X-File-Name':'Identidade-Helpu.webp'},data:fs.readFileSync(new URL('../dist/assets/helpu-motion-poster.webp',import.meta.url))});assert.equal(upload.status(),201);
  async function submit(page,action){const f=page.locator('[data-commercial-form="'+action+'"]');await f.locator('button:not([type])').click();await f.waitFor({state:'hidden'});}
  async function shot(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name);if(await page.locator('#editor').count()&&await page.locator('#editor').evaluate(e=>e.open))assert.equal(await page.locator('#editor').evaluate(e=>e.scrollWidth>e.clientWidth+1),false,'modal '+name);await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
  await o.goto(origin+'/portal.html#/commercial');await o.getByRole('button',{name:'Criar apresentação',exact:true}).click();await o.locator('[name=sector]').selectOption('property');await o.getByRole('button',{name:'Usar texto deste setor'}).click();await o.locator('[name=company]').fill('Imobiliária Exemplo');await o.getByLabel('Identidade-Helpu.webp',{exact:true}).check();await o.locator('[data-caption]').fill('Identidade Helpu. Exemplo ilustrativo de apresentação; sem promessa de resultado.');await submit(o,'save');
  const adminData=await(await op.context.request.get(origin+'/api/portal/commercial-admin')).json(),page=adminData.pages[0];const preview=await op.context.newPage();await preview.goto(origin+'/apresentacao.html?preview='+encodeURIComponent(page.id));await preview.getByText('Prévia restrita da equipe',{exact:true}).waitFor();assert.equal(await preview.locator('[name=consent]').count(),0);await shot(preview,'previa-desktop');await preview.close();
  await o.getByRole('button',{name:'Liberar link público',exact:true}).click();assert.equal(await o.locator('[name=publicConsent]').isChecked(),false);await o.locator('[name=publicConsent]').check();await o.locator('[name=materialConsent]').check();await submit(o,'publish');
  await p.goto(origin+'/apresentacao.html?id='+page.slug);await p.getByRole('heading',{name:'Apresente cada imóvel com uma mensagem clara.'}).waitFor();await p.locator('.example img').evaluate(i=>i.decode());await p.getByRole('button',{name:'03 · Escolha como publicar',exact:true}).click();await p.getByText(/a equipe revisa a versão, obtém sua aprovação/).waitFor();await p.evaluate(()=>scrollTo(0,0));await shot(p,'apresentacao-desktop');
  await p.setViewportSize({width:390,height:1000});await shot(p,'apresentacao-390');await p.setViewportSize({width:320,height:1000});await shot(p,'apresentacao-320');
  await p.getByLabel('Edição de vídeos',{exact:true}).check();await p.getByLabel('Diagnóstico e estratégia',{exact:true}).check();await p.locator('[name=name]').fill('Cliente de teste');await p.locator('[name=email]').fill(customer.email);await p.locator('[name=channel]').selectOption('whatsapp');assert.equal(await p.locator('[name=phone]').isVisible(),true);await p.locator('[name=phone]').fill('+55 54 99999-9999');await p.locator('[name=note]').fill('Gostaria de comparar uma edição avulsa e uma consultoria.');assert.equal(await p.locator('[name=consent]').isChecked(),false);await p.locator('[name=consent]').check();await p.getByRole('button',{name:'Solicitar uma conversa',exact:false}).click();await p.getByRole('heading',{name:'Vamos conversar sobre seu próximo passo.'}).waitFor();await shot(p,'interesse-enviado-320');
  await o.getByRole('button',{name:'Atualizar comercial'}).click();await o.getByRole('button',{name:'Preparar proposta privada'}).click();await o.locator('[name=title]').fill('Primeiro projeto de conteúdo');await o.locator('[name=price]').fill('250');const future=new Date(Date.now()+7*86400000).toISOString().slice(0,10);await o.locator('[name=validUntil]').fill(future);const fields={scope:'Uma empresa, conteúdo para Instagram. Proposta fictícia de teste.',deliverables:'Um vídeo de 15 segundos em 9:16, com material fornecido pelo cliente.',schedule:'Cinco dias úteis após receber os materiais e confirmar o pagamento.',revisions:'Uma revisão consolidada. Suporte para este pedido no chat do portal.',exclusions:'Não inclui filmagem, impulsionamento, postagem ou gestão contínua.',payment:'Pagamento único a combinar com a equipe. Sem renovação automática.',cancellation:'Condições de cancelamento e reembolso a revisar neste exemplo fictício.'};for(const[k]of OFFER_FIELDS)await o.locator('[name="'+k+'"]').fill(fields[k]);await submit(o,'send');await shot(o,'comercial-admin-desktop');
  await c.goto(origin+'/portal.html#/proposals');await c.getByRole('button',{name:'Abrir proposta'}).click();await c.setViewportSize({width:320,height:1000});await shot(c,'proposta-privada-320');await c.getByRole('button',{name:'Pedir ajuste',exact:true}).click();await c.locator('[name=note]').fill('Especificar prazo da revisão');await submit(c,'changes');
  await o.getByRole('button',{name:'Atualizar comercial'}).click();await o.getByRole('button',{name:'Abrir proposta'}).click();await o.getByRole('button',{name:'Preparar nova versão'}).click();await o.locator('[name=revisions]').fill('Uma revisão consolidada, entregue em dois dias úteis.');await submit(o,'send');await c.getByRole('button',{name:'Atualizar propostas'}).click();await c.getByRole('button',{name:'Abrir proposta'}).click();await c.getByRole('button',{name:'Aceitar esta proposta'}).click();await c.locator('[name=consent]').check();await submit(c,'accept');await c.getByRole('button',{name:'Abrir proposta'}).click();await c.getByText(/Aceite registrado para a versão 2/).waitFor();await shot(c,'aceite-320');
  assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.equal((await app.database.prepare('SELECT COUNT(*) AS n FROM jobs').get()).n,0);console.log(JSON.stringify({ok:true,output,checks:['Prévia restrita','Liberação explícita de página e mídia','Página pública 1440/390/320 px','Interesses e canal consentido','Fila comercial','Proposta privada na conta destinatária','Revisão e aceite da segunda versão','Nenhuma mensagem, cobrança ou IA real']}));
}finally{await browser?.close();await app.portal.shutdown();await new Promise(r=>app.close(r));const target=path.resolve(dir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-commercial-visual-'));fs.rmSync(target,{recursive:true,force:true});}
