import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';import {createHelpuServer} from '../server.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-commerce-visual-')),output=path.resolve('../output/planos-producao');fs.mkdirSync(output,{recursive:true});let browser;const env={};
const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,whatsappChatEnv:{}}});await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;
try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});const errors=[];
 async function account(name){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const r=await context.request.post(origin+'/api/auth/signup',{headers:{Origin:origin},data:{name,email:name+'@example.test',password:'only-test-12345',company:name}});assert.equal(r.status(),201);const boot=await(await context.request.get(origin+'/api/portal/bootstrap')).json();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {context,page,boot};}
 const op=await account('Equipe'),customer=await account('Cliente');env.HELPU_OPERATOR_USER_IDS=String(op.boot.user.id);const p=op.page,org=customer.boot.companies[0].id;
 await p.goto(origin+'/admin.html#/commerce');await p.getByRole('heading',{name:'Planos e produção',exact:true}).waitFor();await p.locator('#commerce-org').selectOption(org);
 await p.getByRole('button',{name:'Oferecer plano'}).first().click();await p.locator('[name=start]').fill('2026-09-20');await p.locator('[name=end]').fill('2026-10-20');await p.locator('[name=conditions]').fill('Condições demonstrativas. Sem cobrança real.');await p.getByRole('button',{name:'Confirmar',exact:true}).click();await p.getByText('Proposta para aprovação',{exact:false}).waitFor();
 await customer.context.request.post(origin+'/api/portal/'+org+'/onboarding',{headers:{Origin:origin},data:{action:'skip'}});const cp=customer.page;await cp.goto(origin+'/portal.html#/commerce');await cp.getByRole('button',{name:'Revisar e aceitar'}).click();await cp.locator('#commerce-form input[type=checkbox]').check();await cp.getByRole('button',{name:'Confirmar',exact:true}).click();await cp.getByText('Aceite registrado',{exact:false}).waitFor();
 async function shot(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name);await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
 await p.reload();await p.getByRole('button',{name:'Ativar após pagamento'}).count();await p.locator('#commerce-org').selectOption(org);await p.getByRole('button',{name:'Ativar após pagamento'}).waitFor();await shot(p,'admin');await shot(cp,'cliente');
 for(const width of [390,320]){await cp.setViewportSize({width,height:1000});await shot(cp,'cliente-'+width);await p.setViewportSize({width,height:1000});await shot(p,'admin-'+width);}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,output,checks:['offer','customer accepts terms','admin activation gate','desktop/mobile','no page errors']}));
}finally{await browser?.close();await app.portal.shutdown();await new Promise(r=>app.close(r));const target=path.resolve(dir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-commerce-visual-'));fs.rmSync(target,{recursive:true,force:true});}
