import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {createHelpuServer} from '../server.mjs';
import {testPng} from './image-fixture.mjs';
import {BRIEF_REQUIRED,CONSULTATION_TYPES,REPORT_FIELDS} from '../dist/assets/consultation-schema.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-consultations-visual-')),output=path.resolve('../output/f08');fs.mkdirSync(output,{recursive:true});let browser;const env={};
const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,whatsappChatEnv:{}}});await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;
try{
  browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});
  async function account(name){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',timezoneId:'America/Sao_Paulo'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const res=await context.request.post(origin+'/api/auth/signup',{headers:{Origin:origin},data:{name,email:name.replaceAll(' ','').toLowerCase()+'@example.test',password:'only-test-12345',company:name}});assert.equal(res.status(),201);const boot=await(await context.request.get(origin+'/api/portal/bootstrap')).json();await context.request.post(origin+'/api/portal/'+boot.companies[0].id+'/onboarding',{headers:{Origin:origin},data:{action:'skip'}});return {context,page:await context.newPage(),boot};}
  const client=await account('Cliente Consultoria'),operator=await account('Operador Consultoria');env.HELPU_OPERATOR_USER_IDS=String(operator.boot.user.id);const p=client.page,o=operator.page,errors=[];for(const page of [p,o])page.on('pageerror',e=>errors.push(e.message));
  async function submit(page,action){const f=page.locator('[data-consult-form="'+action+'"]');await f.locator('button:not([type])').click();await f.waitFor({state:'hidden'});}
  async function open(page,title){await page.getByRole('button',{name:'Atualizar consultorias',exact:true}).click();await page.getByRole('button',{name:'Abrir consultoria',exact:true}).click();if(title)await page.getByRole('button',{name:title,exact:true}).click();}
  async function shot(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name);if(await page.locator('#editor').evaluate(e=>e.open))assert.equal(await page.locator('#editor').evaluate(e=>e.scrollWidth>e.clientWidth+1),false,'modal '+name);await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
  await p.goto(origin+'/portal.html#/consultations');await p.getByRole('button',{name:'Solicitar consultoria',exact:true}).click();await p.locator('[name=company]').fill('Empresa Exemplo');await submit(p,'save');await p.getByRole('button',{name:'Editar briefing',exact:true}).click();assert.equal(await p.locator('[name=company]').inputValue(),'Empresa Exemplo');
  for(const k of [...BRIEF_REQUIRED,...CONSULTATION_TYPES.diagnosis.fields.map(([k])=>k)])await p.locator('[data-consult-form] [name="'+k+'"]').fill(k==='company'?'Empresa Exemplo':'Contexto da empresa para '+k);
  await p.locator('[name=channels]').fill('https://example.test');await p.locator('[data-consult-upload=brief]').setInputFiles({name:'referencia.png',mimeType:'image/png',buffer:testPng()});await p.getByText('referencia.png',{exact:true}).waitFor();await shot(p,'briefing-desktop');await submit(p,'save');await p.getByRole('button',{name:'Enviar para análise',exact:true}).click();assert.equal(await p.locator('[name=consent]').isChecked(),false);await p.locator('[name=consent]').check();await submit(p,'submit');
  await o.goto(origin+'/portal.html#/consultations-admin');await open(o,'Preparar proposta');const fields={scope:'Diagnóstico de uma empresa e três canais',deliverables:'Resumo executivo, evidências e plano de 30 dias',exclusions:'Não inclui gestão contínua ou criação de site',price:'250',businessDays:'5',revisions:'1',revisionBusinessDays:'2',deadlineRule:'Dias úteis em Brasília. Feriados locais combinados antes do aceite.',paymentInstructions:'Confirmar a forma de pagamento com a equipe.'};for(const[k,v]of Object.entries(fields))await o.locator('[name="'+k+'"]').fill(v);await submit(o,'propose');await shot(o,'fila-admin-desktop');
  await open(p,'Aceitar proposta');await p.setViewportSize({width:390,height:1000});await shot(p,'proposta-celular');await p.locator('[name=consent]').check();await submit(p,'accept_proposal');
  await open(o,'Conferir pagamento');await o.locator('[name=note]').fill('Recebimento fictício conferido para este teste local');await o.locator('[name=confirmed]').check();await submit(o,'payment');await open(o,'Confirmar briefing completo');await o.locator('[name=confirmed]').check();await submit(o,'brief_complete');await open(o,'Iniciar consultoria');await submit(o,'start');
  await open(o,'Preparar entrega');await o.locator('[name=summary]').fill('Primeiro rascunho interno');await o.getByRole('button',{name:'Salvar rascunho da entrega',exact:true}).click();await o.locator('[data-consult-form]').waitFor({state:'hidden'});await open(o,'Preparar entrega');assert.equal(await o.locator('[name=summary]').inputValue(),'Primeiro rascunho interno');
  const content={summary:'A oferta precisa aparecer antes da lista de serviços. Prioridade: clareza no primeiro contato.',evidence:'Página inicial, consultada em 20/09/2026: https://example.test. Na amostra analisada, o contato está somente no rodapé.',comparison:'Amostra limitada aos três canais fornecidos pelo cliente.',facts:'A página apresenta cinco serviços, mas não informa a cidade no título.',hypotheses:'Uma chamada local pode reduzir dúvidas. Validar em conversas com clientes.',priorities:'Impacto alto e esforço baixo: esclarecer público, cidade e forma de contato no início da página.',roadmap:'Semana 1: responsável comercial ajusta a mensagem. Semana 2: equipe mede dúvidas recebidas. Semana 3: revisar a chamada.',guidance:'Preservar a paleta atual; usar títulos curtos e chamadas específicas.'};for(const[k]of REPORT_FIELDS)await o.locator('[name="'+k+'"]').fill(content[k]);
  await o.locator('[data-consult-upload=delivery]').setInputFiles({name:'guia-visual.png',mimeType:'image/png',buffer:testPng()});await o.getByText('guia-visual.png',{exact:true}).waitFor();await submit(o,'deliver');await open(p);await p.getByText('ENTREGA 1',{exact:false}).waitFor();await p.setViewportSize({width:320,height:1000});await shot(p,'entrega-320');await p.getByRole('button',{name:'Solicitar revisão incluída',exact:true}).click();await p.locator('[name=note]').fill('Detalhar a primeira semana do plano');await submit(p,'revise');
  await open(o,'Preparar entrega');await o.locator('[name=roadmap]').fill(content.roadmap+' Segunda-feira: revisar o título. Terça: atualizar o contato.');await submit(o,'deliver');await open(p,'Aceitar entrega final');await p.locator('[name=consent]').check();await submit(p,'complete');await shot(p,'concluida-320');await o.setViewportSize({width:320,height:1000});await o.getByRole('button',{name:'Atualizar consultorias',exact:true}).click();await shot(o,'admin-320');
  assert.deepEqual(errors,[]);assert.equal((await app.database.prepare('SELECT COUNT(*) AS count FROM jobs').get()).count,0);console.log(JSON.stringify({ok:true,output,checks:['Rascunho e anexos do cliente','Proposta e aceite explícito','Conferência manual de pagamento e briefing','Rascunho de entrega preservado','Entrega privada com arquivo','Revisão e aceite final','1440, 390 e 320 px','Nenhuma mensagem, cobrança ou IA real']}));
}finally{await browser?.close();await app.portal.shutdown();await new Promise(r=>app.close(r));const target=path.resolve(dir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-consultations-visual-'));fs.rmSync(target,{recursive:true,force:true});}
