import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';import {createHelpuServer} from '../server.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-finance-visual-')),output=path.resolve('../output/f12-financeiro');fs.mkdirSync(output,{recursive:true});let browser;const env={};
const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,whatsappChatEnv:{}}});await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;
try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});const errors=[];
 async function account(name){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const r=await context.request.post(origin+'/api/auth/signup',{headers:{Origin:origin},data:{name,email:name+'@example.test',password:'only-test-12345',company:name}});assert.equal(r.status(),201);const boot=await(await context.request.get(origin+'/api/portal/bootstrap')).json();const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {context,page,boot};}
 const op=await account('Equipe'),customer=await account('Cliente');env.HELPU_OPERATOR_USER_IDS=String(op.boot.user.id);const p=op.page;
 await p.goto(origin+'/admin.html#/finance');await p.getByRole('heading',{name:'Financeiro',exact:true}).waitFor();
 await p.getByRole('button',{name:'Nova cobrança'}).click();await p.locator('[name=orgId]').selectOption(customer.boot.companies[0].id);await p.locator('[name=description]').fill('Conteúdo mensal — exemplo');await p.locator('[name=reference]').fill('CONTRATO-DEMONSTRACAO');await p.locator('[name=competence]').fill('2026-09');await p.locator('[name=amount]').fill('397.00');await p.locator('[name=dueDate]').fill('2026-09-30');await p.locator('[name=terms]').fill('Condições fictícias para validar a tela. Nenhuma cobrança real.');await p.getByRole('button',{name:'Registrar cobrança'}).click();await p.getByRole('button',{name:'Abrir cobrança'}).waitFor();
 async function shot(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name);await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
 await shot(p,'financeiro-admin');await p.getByRole('button',{name:'Abrir cobrança'}).click();await p.getByRole('button',{name:'Anexar boleto',exact:true}).click();await p.locator('[name=code]').fill('1'.repeat(47));await p.locator('[name=bankReference]').fill('DEMONSTRACAO');await p.locator('[name=file]').setInputFiles({name:'exemplo.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nexample\n%%EOF')});await p.getByRole('button',{name:'Enviar documento',exact:true}).click();await p.getByRole('button',{name:'Abrir cobrança'}).waitFor();
 await customer.context.request.post(origin+'/api/portal/'+customer.boot.companies[0].id+'/onboarding',{headers:{Origin:origin},data:{action:'skip'}});
 const cp=customer.page;await cp.goto(origin+'/portal.html#/finance');await cp.getByRole('button',{name:'Abrir cobrança'}).waitFor();await shot(cp,'financeiro-cliente');await cp.getByRole('button',{name:'Abrir cobrança'}).click();await cp.getByRole('link',{name:'Baixar boleto PDF'}).waitFor();await shot(cp,'detalhe-cliente');await cp.getByRole('button',{name:'Fechar',exact:true}).click();
 for(const width of [390,320]){await cp.setViewportSize({width,height:1000});await shot(cp,'cliente-'+width);await p.setViewportSize({width,height:1000});await shot(p,'admin-'+width);}
 await cp.getByLabel('Quero receber avisos financeiros no meu WhatsApp conectado.').check();await cp.getByText('Preferência salva.',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,output,checks:['create charge','upload private boleto','customer finance','consent','1440/390/320 px','no page errors']}));
}finally{await browser?.close();await app.portal.shutdown();await new Promise(r=>app.close(r));const target=path.resolve(dir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-finance-visual-'));fs.rmSync(target,{recursive:true,force:true});}