import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright-core';
import {createHelpuServer} from '../server.mjs';
import {PLAN_TERMS,COST_FIELDS} from '../dist/assets/pricing-model.js';
import {COMMERCIAL_SECTORS} from '../dist/assets/commercial-schema.js';
import {pricingFixture} from './pricing-fixture.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-pricing-visual-')),output=path.resolve('../output/f10');fs.mkdirSync(output,{recursive:true});let browser;const env={};
const app=await createHelpuServer({dataDir:dir,portalOptions:{startScheduler:false,operatorEnv:env,whatsappChatEnv:{}}});await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port;
try{
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});
 const errors=[],failed=[];async function account(name){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',timezoneId:'America/Sao_Paulo'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const email=name.toLowerCase()+'@example.test';assert.equal((await context.request.post(origin+'/api/auth/signup',{headers:{Origin:origin},data:{name,email,password:'only-test-12345',company:name}})).status(),201);const boot=await(await context.request.get(origin+'/api/portal/bootstrap')).json();await context.request.post(origin+'/api/portal/'+boot.companies[0].id+'/onboarding',{headers:{Origin:origin},data:{action:'skip'}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url()+' '+r.status());});return {context,page,boot,email};}
 const op=await account('EquipePrecos'),client=await account('ClientePrecos'),p=op.page;env.HELPU_OPERATOR_USER_IDS=String(op.boot.user.id);
 const post=async(route,data,ctx=op.context)=>{const r=await ctx.request.post(origin+route,{headers:{Origin:origin},data});assert.equal(r.status(),200,await r.text());return r.json();};
 async function shot(name){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name);if(await p.locator('#editor').evaluate(e=>e.open))assert.equal(await p.locator('#editor').evaluate(e=>e.scrollWidth>e.clientWidth+1),false,'modal '+name);await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
 async function submit(action){const f=p.locator('[data-pricing-form="'+action+'"]');await f.locator('button:not([type])').click();await f.waitFor({state:'hidden'});}
 await p.goto(origin+'/portal.html#/pricing');await p.getByRole('button',{name:'Estruturar oferta',exact:true}).click();await p.locator('[name=name]').fill('Rascunho incompleto de teste');await submit('save');await p.getByRole('button',{name:'Editar ficha',exact:true}).click();assert.equal(await p.locator('[data-line=unitCostCents]').inputValue(),'');
 let posts=0;p.on('request',r=>{if(r.method()==='POST')posts++;});const before=posts,f=pricingFixture();await p.locator('[name=name]').fill(f.name);for(const [key,value]of Object.entries(f.lines[0])){const el=p.locator('[data-line="'+key+'"]');if(['unit','confidence'].includes(key))await el.selectOption(value);else await el.fill(String(key==='unitCostCents'?value/100:value));}
 for(const [key,,type]of COST_FIELDS)await p.locator('[name="'+key+'"]').fill(String(['money','percent'].includes(type)?f.costs[key]/100:f.costs[key]));await p.locator('[name=costReference]').fill(f.costReference);await p.locator('[name=observedDate]').fill(f.observedDate);
 await p.getByText('3. Stripe e boleto manual',{exact:true}).click();for(const c of f.channels){for(const [suffix,v]of [['percent',c.percentBps/100],['fixed',c.fixedCents/100],['minutes',c.minutes],['reference',c.reference]])await p.locator('[name="'+c.id+'_'+suffix+'"]').fill(String(v));}
 await p.getByText('4. Ficha completa do que o cliente recebe',{exact:true}).click();for(const[key]of PLAN_TERMS)await p.locator('[name="term_'+key+'"]').fill(f.terms[key]);await p.locator('[name=regularPrice]').fill('150');assert.equal(posts,before,'local simulation has no POST');await p.locator('[data-pricing-simulation]').getByText('Ficha preenchida.',{exact:false}).waitFor();await submit('save');
 await p.getByRole('button',{name:'Revisar para propostas',exact:true}).click();assert.equal(await p.locator('[name=confirmed]').isChecked(),false);assert.equal(await p.locator('[name=capacityConfirmed]').isChecked(),false);await p.locator('[name=confirmed]').check();await p.locator('[name=capacityConfirmed]').check();await shot('revisao-desktop');await submit('review');await p.getByRole('button',{name:'Abrir ficha',exact:true}).click();await shot('simulacao-desktop');await p.setViewportSize({width:390,height:1000});await shot('simulacao-390');await p.setViewportSize({width:320,height:1000});await shot('simulacao-320');await p.getByRole('button',{name:'Editar ficha',exact:true}).click();await shot('formulario-320');await p.locator('#editor').evaluate(e=>e.close());await p.goto(origin+'/portal.html#/pricing');await p.getByText('Revisada internamente',{exact:false}).first().waitFor();await shot('planos-320');
 // Consent and source setup use the same API as F09; no real contacts are created.
 let page=await post('/api/portal/commercial-admin',{kind:'page',action:'save',requestKey:randomUUID(),orgId:op.boot.companies[0].id,sector:'general',...COMMERCIAL_SECTORS.general,company:'Empresa fictícia',media:[]});page=await post('/api/portal/commercial-admin',{kind:'page',action:'publish',id:page.id,version:page.version,publicConsent:true,materialConsent:true});await post('/api/presentations/'+page.slug+'/interest',{name:'Cliente de teste',company:'Empresa fictícia',email:client.email,channel:'email',interests:['content'],consent:true,requestKey:randomUUID()},client.context);
 await p.setViewportSize({width:1440,height:1000});await p.goto(origin+'/portal.html#/commercial');await p.getByRole('button',{name:'Preparar proposta privada',exact:true}).click();const option=await p.locator('[name=pricingSource] option').last().getAttribute('value');await p.locator('[name=pricingSource]').selectOption(option);await p.getByRole('button',{name:'Preencher com esta ficha',exact:true}).click();assert.equal(await p.locator('[name=price]').inputValue(),'150');assert.match(await p.locator('[name=deliverables]').inputValue(),/4 × Imagem final/);assert.doesNotMatch(await p.locator('[data-commercial-form]').innerText(),/PRIVATE-/);await p.locator('[name=validUntil]').fill(new Date(Date.now()+7*86400000).toISOString().slice(0,10));await p.locator('[data-commercial-form] button:not([type])').click();await p.locator('[data-commercial-form]').waitFor({state:'hidden'});
 await client.page.goto(origin+'/portal.html#/proposals');assert.equal(await client.page.getByRole('link',{name:'Planos e custos',exact:true}).count(),0);await client.page.getByRole('button',{name:'Abrir proposta',exact:true}).click();assert.doesNotMatch(await client.page.locator('#editor').innerText(),/PRIVATE-|Margem normal|Custo antes/);await client.page.setViewportSize({width:320,height:1000});await client.page.screenshot({path:path.join(output,'proposta-cliente-320.png'),fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.equal((await app.database.prepare('SELECT COUNT(*) AS n FROM jobs').get()).n,0);console.log(JSON.stringify({ok:true,output,checks:['Rascunho sem transformar vazios em zero','Simulação local sem requisições de execução','Revisão interna explícita','Desktop e 390/320 px sem rolagem horizontal','Oferta revisada preenche proposta','Destinatário não vê custos nem margens','Nenhuma cobrança, mensagem ou IA real']}));
}finally{await browser?.close();await app.portal.shutdown();await new Promise(r=>app.close(r));const target=path.resolve(dir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-pricing-visual-'));fs.rmSync(target,{recursive:true,force:true});}
