import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {chromium} from 'playwright-core';
import {createHelpuServer} from '../server.mjs';

// Deliberately separate from npm test: needs installed Chrome and visual inspection.
// Every account, brand fact, model response and file belongs to this temporary fixture.
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-visual-smoke-'));
const dataDir=path.join(directory,'data');
const screenshots=path.join(directory,'screenshots');fs.mkdirSync(screenshots);
const executablePath=process.env.HELPU_VISUAL_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe';
assert.ok(fs.existsSync(executablePath),'Set HELPU_VISUAL_BROWSER to an installed Chrome executable.');
delete process.env.HELPU_PUBLIC_URL;
let browser,externalAttempts=0,modelCalls=0;
const providers=new Proxy({}, {get:()=>async()=>{externalAttempts++;throw new Error('TEST ONLY: external actions are disabled in visual QA.');}});
const server=createHelpuServer({dataDir,portalOptions:{startScheduler:false,providers,conversationRespond:async()=>{modelCalls++;return {status:'completed',output:[{type:'function_call',name:'deliver_post',call_id:randomUUID(),arguments:JSON.stringify({title:'TEST ONLY: identidade em movimento',concept:'TEST ONLY: apresentar uma identidade fictícia de teste.',caption:'TEST ONLY: uma publicação para verificar o fluxo local da Helpu.',visualBrief:'TEST ONLY: composição simples com azul #123456 e branco, sem fotografia.'})}]};}}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin='http://127.0.0.1:'+server.address().port;
const errors=[],checks=[],shots=[],layout=[];
try{
 browser=await chromium.launch({executablePath,headless:true,args:['--disable-background-networking','--disable-component-update','--no-first-run']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',timezoneId:'America/Sao_Paulo',reducedMotion:'reduce'});
 await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));
 const shot=async(name,{focus,fullPage=true}={})=>{await page.waitForFunction(()=>!document.querySelector('#toast')||document.querySelector('#toast').hidden);await page.evaluate(()=>window.scrollTo(0,0));if(focus)await page.locator(focus).scrollIntoViewIfNeeded();layout.push({name,...await page.evaluate(()=>{const skip=document.querySelector('.p-skip');return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,skipBottom:skip?.getBoundingClientRect().bottom,skipFocused:document.activeElement===skip,active:document.activeElement?.tagName};})});const file=path.join(screenshots,name+'.png');await page.screenshot({path:file,fullPage,animations:'disabled'});shots.push(file);};
 const localApi=async(tail,method='GET',data)=>page.evaluate(async({tail,method,data})=>{const response=await fetch(tail,{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;},{tail,method,data});
 const nav=async route=>{const link=page.locator('#portal-nav a[href="#/'+route+'"]');if(!await link.isVisible())await page.locator('#navigation-more').click();await link.click();await page.waitForFunction(route=>document.body.dataset.view===route,route);assert.equal(await page.locator('#workspace h1').count(),1);};
 await page.goto(origin+'/');await page.locator('h1').waitFor();assert.match(await page.title(),/Helpu/i);await shot('01-landing-desktop');checks.push('Landing local carregada.');
 await page.locator('a[href="cadastro.html"]').first().click();await page.locator('[data-auth="signup"]').waitFor();
 await page.locator('input[name="name"]').fill('TEST ONLY Operador');await page.locator('input[name="company"]').fill('TEST ONLY EME');await page.locator('input[name="email"]').fill('visual-smoke@example.test');await page.locator('input[name="password"]').fill('test-only-visual-password');await shot('02-cadastro-desktop');await page.locator('[data-auth="signup"] [type="submit"]').click();await page.waitForURL('**/portal.html');await page.locator('#conversation-prompt').waitFor();
 assert.equal(await page.locator('#portal-nav a').count(),17);checks.push('Cadastro sintético pelo formulário e 17 áreas preservadas.');
 await page.locator('#user-menu').click();await page.locator('#portal-logout').click();await page.waitForURL('**/entrar.html');await page.locator('#email').fill('visual-smoke@example.test');await page.locator('#password').fill('test-only-visual-password');await shot('03-login-desktop');await page.locator('[data-auth="login"] [type="submit"]').click();await page.waitForURL('**/portal.html');await page.locator('#conversation-prompt').waitFor();checks.push('Logout e login pelo formulário preservados.');
 const bootstrap=await localApi('/api/portal/bootstrap'),org=bootstrap.companies[0].id;const api=(tail,method,data)=>localApi('/api/portal/'+org+'/'+tail,method,data);
 await page.locator('#new-company').click();await page.locator('#f-name').fill('TEST ONLY Segunda');await page.locator('#dialog-form [type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#company-select option:checked')?.textContent==='TEST ONLY Segunda');await page.locator('#company-select').selectOption(org);await page.waitForFunction(()=>document.querySelector('#breadcrumb-company')?.textContent==='TEST ONLY EME');checks.push('Criação de segunda empresa e troca de empresa pelo seletor.');
 await nav('brand');await page.locator('#f-description').fill('TEST ONLY: empresa fictícia de validação de software.');await page.locator('#f-audience').fill('TEST ONLY: pessoas que validam fluxos locais.');await page.locator('#f-tone').fill('TEST ONLY: claro e direto.');await page.locator('#f-visualIdentity').fill('TEST ONLY: azul #123456, branco e composição simples.');await page.locator('#f-restrictions').fill('TEST ONLY: não inventar preços, clientes, métricas ou publicações.');await page.locator('#brand-form [type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent==='Informações salvas.');assert.match((await api('state')).company.profile.description,/TEST ONLY/);checks.push('Contexto sintético salvo por Marca e negócio.');
 // Only a synthetic marker enables the injected model; no provider API is invoked.
 await api('integrations/openai','PUT',{apiKey:'TEST-ONLY-NOT-A-REAL-KEY'});
 await nav('conversation');await page.locator('#conversation-prompt').fill('Prepare uma publicação para a TEST ONLY EME seguindo a identidade da empresa.');const submitted=page.waitForResponse(r=>r.request().method()==='POST'&&/\/conversations\/[^/]+\/messages$/.test(new URL(r.url()).pathname));await page.locator('.send-prompt').click();const submission=await (await submitted).json();assert.ok(submission.payload.operationId);await server.portal.tick();await page.locator('.operation-context').waitFor();await page.getByRole('button',{name:'Aprovar entregas',exact:true}).waitFor();await shot('04-operacao-revisao-desktop');
 let state=await api('state');assert.equal(state.operations[0].state,'awaiting_approval');assert.equal(state.records.content.length,1);assert.equal(state.records.tasks.length,4);checks.push('Chat criou ordem, campanha, quatro tarefas e uma entrega com revisão pendente.');
 await page.getByRole('button',{name:'Aprovar entregas',exact:true}).click();await page.getByRole('button',{name:'Executar publicação',exact:true}).waitFor();assert.equal((await api('state')).operations[0].state,'ready');checks.push('Aprovação inline liberou a versão real sem publicar.');
 await nav('campaigns');assert.equal(await page.locator('.campaign-card').count(),1);assert.match(await page.locator('.campaign-card').innerText(),/Pronta para execução/);await shot('05-campanha-desktop');
 await nav('studio');assert.equal(await page.locator('.content-card').count(),1);await page.locator('.content-thumbnail').click();await page.getByText('Entrega atual: conceito, legenda e briefing criativo. A imagem ainda não foi gerada ou anexada.',{exact:true}).waitFor();await shot('06-estudio-dialogo-desktop');await page.locator('#dialog-close').click();
 await nav('tasks');assert.equal(await page.locator('.task-row').count(),4);assert.equal(await page.locator('.task-check:disabled').count(),4);await shot('07-tarefas-desktop');
 await nav('calendar');assert.equal(await page.locator('.calendar-event').count(),0);await shot('08-calendario-sem-data-desktop');checks.push('Campanha, Estúdio e tarefas refletem a mesma operação; calendário não inventa agendamento.');
 await nav('results');await page.getByRole('heading',{name:'Operações e evidências',exact:true}).waitFor();assert.match(await page.locator('#workspace').innerText(),/Nenhuma execução externa comprovada/);assert.equal((await api('state')).records.metrics.length,0);await shot('09-resultados-desktop');
 await nav('settings');await page.getByRole('button',{name:'+ Adicionar regra',exact:true}).click();const rule=page.locator('[data-operation-rule]').last();await rule.locator('[data-rule-field="channel"]').selectOption('instagram');await rule.locator('[data-rule-field="action"]').selectOption('publish');await rule.locator('[data-rule-field="risk"]').selectOption('high');await rule.locator('[data-rule-field="policy"]').selectOption('forbidden');await page.locator('#settings-form [type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent==='Informações salvas.');assert.equal((await api('state')).company.policy.operationRules[0].policy,'forbidden');await shot('10-autonomia-desktop');checks.push('Resultados mostram ausência de métricas e de execução externa comprovada; regra de Autonomia salva pelo formulário.');
 await nav('activity');assert.match(await page.locator('#workspace').innerText(),/Operações da conversa/);await shot('11-atividades-desktop');await nav('overview');await page.getByRole('heading',{name:'Objetivos em andamento',exact:true}).waitFor();
 await nav('conversation');await page.getByRole('button',{name:'Executar publicação',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});await shot('12-conversa-mobile',{focus:'.operation-context',fullPage:false});assert.ok(await page.locator('#conversation-prompt').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
 await nav('studio');await shot('13-estudio-mobile');await nav('tasks');await shot('14-tarefas-mobile');await nav('settings');await shot('15-autonomia-mobile');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));checks.push('Conversa, Estúdio, tarefas e Autonomia capturados em 390px; sem overflow horizontal nos pontos verificados.');
 const other=(await localApi('/api/portal/bootstrap')).companies.find(c=>c.id!==org);await page.locator('#company-select').selectOption(other.id);await page.waitForFunction(()=>document.querySelector('#breadcrumb-company')?.textContent==='TEST ONLY Segunda');const otherState=await localApi('/api/portal/'+other.id+'/state');assert.equal(otherState.operations.length,0);assert.equal(otherState.records.content.length,0);await nav('conversation');assert.equal(await page.locator('.operation-context').count(),0);checks.push('Outra empresa continua vazia e a conversa não vaza a operação.');
 assert.equal(externalAttempts,0);assert.equal(modelCalls,1);assert.deepEqual(errors,[]);checks.push('Sem erros de JavaScript; uma resposta de modelo simulada; zero chamadas de provedores externos.');
 const report={origin,directory,checks,screenshots:shots,layout,modelCalls,externalAttempts,errors};fs.writeFileSync(path.join(directory,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){console.error('VISUAL QA FAILED:',error);console.error('Temporary fixture:',directory);throw error;}
finally{await browser?.close();await server.portal.shutdown();await new Promise(resolve=>server.close(resolve));}