import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHmac,randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {createDatabase} from '../portal/database.mjs';
import {createHelpuServer} from '../server.mjs';

for(const postgres of [false,true])test('Atendimento manual sem alterar o canal Astra: '+(postgres?'PostgreSQL':'SQLite'),async t=>{
 const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'helpu-manual-test-')),sent=[],operatorEnv={};
 const env={HELPU_WHATSAPP_BATCH_MS:'0',HELPU_WHATSAPP_NUMBER:'15551234567',HELPU_WHATSAPP_PHONE_NUMBER_ID:'official',HELPU_WHATSAPP_ACCESS_TOKEN:'fake-token',HELPU_WHATSAPP_APP_SECRET:'fake-secret',HELPU_WHATSAPP_VERIFY_TOKEN:'fake-verify',HELPU_WHATSAPP_MANUAL_TEMPLATES_JSON:JSON.stringify([{name:'helpu_atendimento',language:'pt_BR',parameters:1,text:'Olá, {{1}}. Podemos conversar?',label:'Iniciar atendimento'}])};
 let database,pg,behavior='ok',modelCalls=0,downloads=0;
 if(postgres){pg=await PGlite.create({parsers:{20:Number}});await pg.exec('CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA storage; CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint);');for(const file of ['20260913113000_preserve_helpu_data.sql','20260913140000_activate_cloud_runtime.sql'])await pg.exec(fs.readFileSync(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));await pg.exec('INSERT INTO helpu.portal_migrations VALUES(1,1),(2,1),(3,1),(4,1); SET ROLE helpu_runtime;');let queued=Promise.resolve();database=createDatabase({pool:{async connect(){const prior=queued;let release;queued=new Promise(r=>release=r);await prior;return {async query(sql,args){const result=await pg.query(sql,args);return {...result,rowCount:result.affectedRows};},release};},async end(){}}});}
 const bytes=Buffer.from([137,80,78,71,13,10,26,10,1,2,3]);
 const app=await createHelpuServer({dataDir,database,portalOptions:{startScheduler:false,operatorEnv,whatsappChatEnv:env,openaiEnv:{OPENAI_API_KEY:'fake-openai'},conversationRespond:async()=>{modelCalls++;return {status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Resposta do Astra'}]}]};},whatsappChatFetch:async(url,req)=>{if(url.includes('/123456?'))return Response.json({url:'https://lookaside.fbsbx.com/manual-test',mime_type:'image/png',file_size:bytes.length});if(url==='https://lookaside.fbsbx.com/manual-test'){downloads++;return new Response(bytes);}if(url.endsWith('/media'))return Response.json({id:'uploaded'});sent.push(JSON.parse(req.body));if(behavior==='timeout')throw Error('timeout secret');if(behavior==='reject')return Response.json({error:{code:132001,message:'private provider error'}},{status:400});return Response.json({messages:[{id:'manual-'+sent.length}]});}}});
 await new Promise(r=>app.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.address().port,db=app.database;
 const request=async(url,method='GET',data,cookie='')=>{const r=await fetch(origin+url,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const signup=async(name,extra={})=>{const a=await request('/api/auth/signup','POST',{name,email:name+'@example.test',password:'only-test-12345',company:'Empresa '+name,...extra});assert.equal(a.status,201);const b=(await request('/api/portal/bootstrap','GET',undefined,a.cookie)).body;return {cookie:a.cookie,user:b.user,org:b.companies[0].id};};
 const op=await signup('Equipe'),customer=await signup('Cliente');operatorEnv.HELPU_OPERATOR_USER_IDS=String(op.user.id);
 const endpoint='/api/portal/whatsapp-manual',phone='5554999998888',linkedPhone='5511988887777';
 const action=d=>request(endpoint,'POST',d,op.cookie),listing=p=>request(endpoint+(p?'?phone='+p:''),'GET',undefined,op.cookie),client=(tail,method='GET',d)=>request('/api/portal/'+customer.org+'/'+tail,method,d,customer.cookie);
 let serial=0;
 const webhook=async(value,valid=true)=>{const body=JSON.stringify({entry:[{changes:[{value:{metadata:{phone_number_id:'official'},...value}}]}]});return fetch(origin+'/webhooks/helpu-whatsapp',{method:'POST',headers:{'Content-Type':'application/json','x-hub-signature-256':'sha256='+createHmac('sha256',valid?env.HELPU_WHATSAPP_APP_SECRET:'bad').update(body).digest('hex')},body});};
 const incoming=(text,p=phone,extra={})=>webhook({messages:[{id:'incoming-'+(++serial),from:p,timestamp:String(Math.floor(Date.now()/1000)),type:'text',text:{body:text},...extra}]});
 const tick=()=>db.scope(()=>app.portal.tick());
 try{
  await t.test('só equipe; caixa desativada não captura nem altera mensagens',async()=>{assert.equal((await request(endpoint)).status,401);assert.equal((await request(endpoint,'GET',undefined,customer.cookie)).status,403);assert.equal((await listing()).body.enabled,false);await incoming('Olá');assert.equal((await listing()).body.contacts.length,0);assert.equal((await action({action:'enable'})).status,422);assert.equal((await action({action:'enable',confirmed:true})).status,200);});
  await t.test('prospect sem cadastro: recebe, deduplica e envia sem consumir IA',async()=>{await incoming('Quero conhecer a Helpu',phone,{id:'same'});await incoming('Quero conhecer a Helpu',phone,{id:'same'});assert.equal((await listing(phone)).body.messages.length,1);const payload={action:'send',phone,text:'Olá! Vamos conversar.',requestId:randomUUID()};const count=sent.length;assert.equal((await action(payload)).body.state,'accepted');assert.equal((await action(payload)).body.state,'accepted');assert.equal(sent.length,count+1);assert.equal((await action({...payload,text:'Outra mensagem'})).status,409);await tick();assert.equal(modelCalls,0);});
  await t.test('status exige destinatário certo e não regride',async()=>{const m=(await listing(phone)).body.messages.find(m=>m.direction==='outgoing');await webhook({statuses:[{id:m.providerId,recipient_id:'5511977776666',status:'read'}]});assert.equal((await listing(phone)).body.messages.find(x=>x.id===m.id).state,'accepted');await webhook({statuses:[{id:m.providerId,recipient_id:phone,status:'read'}]});await webhook({statuses:[{id:m.providerId,recipient_id:phone,status:'sent'}]});assert.equal((await listing(phone)).body.messages.find(x=>x.id===m.id).state,'read');});
  await t.test('timeout não duplica; rejeição não expõe resposta privada',async()=>{const payload={action:'send',phone,text:'Proposta',requestId:randomUUID()};behavior='timeout';assert.equal((await action(payload)).body.state,'uncertain');const n=sent.length;assert.equal((await action(payload)).body.state,'uncertain');assert.equal(sent.length,n);behavior='reject';const r=await action({...payload,requestId:randomUUID()});assert.equal(r.body.state,'failed');assert.ok(!JSON.stringify(r.body).includes('private provider'));behavior='ok';});
  await t.test('primeiro contato exige autorização e modelo; texto livre não inicia conversa',async()=>{const p='+351912345678';assert.equal((await action({action:'contact',phone:p,name:'Prospect'})).status,200);assert.equal((await action({action:'send',phone:p,text:'Olá',requestId:randomUUID()})).status,409);const payload={action:'send',phone:p,template:'helpu_atendimento',language:'pt_BR',parameters:['Maria'],requestId:randomUUID()};assert.equal((await action(payload)).status,409);assert.equal((await action({action:'contact',phone:p,consent:true,evidence:'Formulário de interesse, autorização de atendimento em 21/09.'})).status,200);assert.equal((await action({...payload,template:'nao_configurado'})).status,422);assert.equal((await action(payload)).body.state,'accepted');assert.equal(sent.at(-1).template.components[0].parameters[0].text,'Maria');assert.equal((await action({action:'resume',phone:p,confirmed:true})).status,409);});
  await t.test('anexos são privados, não entram na biblioteca da empresa nem chegam a outros usuários',async()=>{const upload=await fetch(origin+endpoint+'/files?phone='+phone,{method:'POST',headers:{Origin:origin,Cookie:op.cookie,'Content-Type':'image/png','X-File-Name':'proposta.png'},body:bytes});assert.equal(upload.status,201);const asset=await upload.json();assert.equal((await fetch(origin+'/api/portal/files/'+asset.id,{headers:{Cookie:customer.cookie}})).status,403);assert.equal((await fetch(origin+'/api/portal/files/'+asset.id,{headers:{Cookie:op.cookie}})).status,200);await db.prepare('INSERT INTO memberships VALUES(?,?,?)').run(op.org,customer.user.id,'member');assert.equal((await fetch(origin+'/api/portal/files/'+asset.id,{headers:{Cookie:customer.cookie}})).status,403);assert.equal((await request('/api/portal/'+op.org+'/state','GET',undefined,customer.cookie)).body.assets.some(a=>a.id===asset.id),false);await db.prepare('DELETE FROM memberships WHERE org_id=? AND user_id=?').run(op.org,customer.user.id);const state=(await request('/api/portal/'+op.org+'/state','GET',undefined,op.cookie)).body;assert.ok(!state.assets.some(a=>a.id===asset.id));assert.equal((await action({action:'send',phone,text:'Confira',assetId:asset.id,requestId:randomUUID()})).body.state,'accepted');assert.equal(sent.at(-1).image.id,'uploaded');await incoming('',phone,{type:'image',image:{id:'123456',caption:'Referência do contato'}});await tick();await tick();assert.equal(downloads,1);const m=(await listing(phone)).body.messages.find(x=>x.text==='Referência do contato');assert.ok(m.asset);assert.equal(m.media,undefined);assert.equal((await fetch(origin+m.asset.url,{headers:{Cookie:customer.cookie}})).status,403);});
  let thread;
  await t.test('vínculo existente continua normal; assumir bloqueia IA nova e entregas pendentes',async()=>{const s=await client('whatsapp-chat','POST',{phone:linkedPhone,enabled:true,consent:true});assert.equal(s.status,200);const code=new URL(s.body.connectUrl).searchParams.get('text');await incoming(code,linkedPhone);thread=(await client('whatsapp-chat')).body.threadId;assert.equal((await listing(linkedPhone)).body.selected.mode,'astra');assert.equal((await listing(linkedPhone)).body.messages.length,0);await incoming('Converse comigo',linkedPhone);await tick();await tick();assert.equal(modelCalls,1);assert.ok(sent.some(s=>s.text?.body==='Resposta do Astra'));const count=sent.length;await action({action:'take',phone:linkedPhone});await app.portal.conversation.appendMessage(customer.org,thread,'assistant','Entrega pendente de teste');await incoming('Quero atendimento humano',linkedPhone,{id:'manual-before-resume'});await tick();assert.equal(modelCalls,1);assert.equal(sent.length,count);assert.equal((await listing(linkedPhone)).body.selected.mode,'manual');assert.ok((await listing(linkedPhone)).body.messages.some(m=>m.text==='Quero atendimento humano'));});
  await t.test('retomada é explícita; manual não vira pedido Astra; pausa persiste entre requisições',async()=>{assert.equal((await action({action:'resume',phone:linkedPhone})).status,422);assert.equal((await listing(linkedPhone)).body.selected.mode,'manual');assert.equal((await action({action:'resume',phone:linkedPhone,confirmed:true})).status,200);await incoming('Quero atendimento humano',linkedPhone,{id:'manual-before-resume'});await tick();assert.equal(sent.filter(s=>s.text?.body==='Entrega pendente de teste').length,1);assert.equal(modelCalls,1);await incoming('Mais uma conversa',linkedPhone);await tick();assert.equal(modelCalls,2);const conversation=(await client('conversations/'+thread)).body;assert.ok(!conversation.messages.some(m=>m.role==='user'&&m.text==='Quero atendimento humano'));});
  await t.test('SAIR bloqueia manual mesmo recebido com Astra ativo',async()=>{await incoming('SAIR',linkedPhone);assert.equal((await client('whatsapp-chat')).body.enabled,false);await action({action:'take',phone:linkedPhone});assert.equal((await action({action:'send',phone:linkedPhone,text:'Não enviar',requestId:randomUUID()})).status,409);await incoming('SAIR');assert.equal((await listing(phone)).body.selected.suppressed,true);assert.equal((await action({action:'send',phone,text:'Não enviar',requestId:randomUUID()})).status,409);});
  await t.test('boas-vindas personalizada mantém confirmação de vínculo separada e envio único',async()=>{env.HELPU_WHATSAPP_WELCOME_TEMPLATE_V2='helpu_boas_vindas_v2';const welcome=await signup('Maria',{company:'Loja Maria',phone:'54999998887',whatsappWelcomeConsent:true});await app.portal.dispatchSignupWelcome();await app.portal.dispatchSignupWelcome();const messages=sent.filter(s=>s.template?.name==='helpu_boas_vindas_v2');assert.equal(messages.length,1);assert.deepEqual(messages[0].template.components[0].parameters,[{type:'text',text:'Maria'},{type:'text',text:'Loja Maria'}]);assert.equal((await request('/api/portal/'+welcome.org+'/whatsapp-chat','GET',undefined,welcome.cookie)).body.enabled,false);});
 }finally{await app.portal.shutdown();await new Promise(r=>app.close(r));await pg?.close();const target=path.resolve(dataDir);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep+'helpu-manual-test-'));fs.rmSync(target,{recursive:true,force:true});}
});
