import fs from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {ProviderError} from './providers.mjs';
import {findBrowser} from '../scripts/runtime.mjs';
export const BROWSER_CHANNELS=[
 {id:'instagram',name:'Instagram',url:'https://www.instagram.com/',domains:['instagram.com']},
 {id:'whatsapp',name:'WhatsApp Web',url:'https://web.whatsapp.com/',domains:['whatsapp.com']},
 {id:'google',name:'Perfil da Empresa no Google',url:'https://business.google.com/',domains:['google.com','google.com.br']},
 {id:'higgsfield',name:'Higgsfield',url:'https://higgsfield.ai/',domains:['higgsfield.ai']}
];
export function createBrowserManager({db,dataDir,launch,assetPath}){
 const sessions=new Map(),opening=new Map();
 db.prepare("UPDATE browser_profiles SET automation_allowed=0,uncertain_note=COALESCE(uncertain_note,'Uma interação foi interrompida. Confira o resultado na conta antes de liberar a sessão.') WHERE pending_job_id IS NOT NULL").run();
 db.prepare("UPDATE browser_profiles SET automation_allowed=0,uncertain_note=COALESCE(uncertain_note,'A conversa foi interrompida após operar esta conta. Confira os passos antes de liberar a sessão.') WHERE EXISTS (SELECT 1 FROM jobs j,json_each(j.external,'$.browserChannels') channel WHERE j.org_id=browser_profiles.org_id AND j.kind='conversation' AND j.state IN ('working','uncertain') AND json_extract(j.external,'$.conversationEffectsStarted')=1 AND channel.value=browser_profiles.channel)").run();
 const key=(org,channel)=>org+':'+channel;
 const definition=channel=>{const d=BROWSER_CHANNELS.find(c=>c.id===channel);if(!d)throw new ProviderError('Canal de navegador não disponível.','blocked');return d;};
 const validUrl=(value,channel)=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&definition(channel).domains.some(d=>u.hostname===d||u.hostname.endsWith('.'+d));}catch{return false;}};
 function localOnly(){if(process.env.HELPU_PUBLIC_URL)throw new ProviderError('O navegador local precisa ser operado no computador da Helpu. A conexão com uma instalação em nuvem requer o companion pareado.','blocked');}
 function list(org){return BROWSER_CHANNELS.map(d=>{const p=db.prepare('SELECT * FROM browser_profiles WHERE org_id=? AND channel=?').get(org,d.id);const s=sessions.get(key(org,d.id));return {id:d.id,name:d.name,accountLabel:p?.account_label||'',confirmedAt:p?.confirmed_at||null,automationAllowed:!!p?.automation_allowed,open:!!s,saved:!!p,busy:!!s?.owner,uncertainNote:p?.uncertain_note||null,challenge:s?.challenge||false,url:s?.page?.url()||null,local:true};});}
 async function open(org,channel){localOnly();definition(channel);const k=key(org,channel);if(sessions.has(k)){await sessions.get(k).page.bringToFront();return list(org).find(x=>x.id===channel);}if(opening.has(k))return opening.get(k);
  const promise=(async()=>{const profile=path.join(dataDir,'browser-profiles',org,channel);fs.mkdirSync(profile,{recursive:true});let context;
   try{if(launch)context=await launch(profile);else{const {chromium}=await import('playwright-core');const executablePath=findBrowser();if(!executablePath)throw new Error('browser-not-installed');context=await chromium.launchPersistentContext(profile,{executablePath,headless:false,viewport:{width:1280,height:820},acceptDownloads:false,serviceWorkers:'block',args:['--disable-background-networking']});}}catch{throw new ProviderError('Não foi possível abrir o navegador. Instale as dependências do projeto e mantenha Chrome ou Edge instalado neste computador.','blocked');}
   await context.route('**/*',route=>{const req=route.request();let u;try{u=new URL(req.url());}catch{return route.abort();}if(/^(localhost|127\.|0\.|10\.|192\.168\.|169\.254\.|\[)/i.test(u.hostname)||/\.(local|internal)$/i.test(u.hostname))return route.abort();if(req.isNavigationRequest()&&!validUrl(u.href,channel)&&u.href!=='about:blank')return route.abort();return route.continue();});
   const page=context.pages()[0]||await context.newPage();const s={context,page,owner:null,token:null,refs:new Set(),challenge:false,lastObserved:0};sessions.set(k,s);
   context.on('page',p=>{p.on('download',d=>d.cancel().catch(()=>{}));});context.on('close',()=>{sessions.delete(k);});page.on('download',d=>d.cancel().catch(()=>{}));page.on('filechooser',chooser=>{s.chooser=chooser;});
   db.prepare('INSERT INTO browser_profiles(org_id,channel,updated_at) VALUES(?,?,?) ON CONFLICT(org_id,channel) DO UPDATE SET updated_at=excluded.updated_at').run(org,channel,Date.now());
   try{await page.goto(definition(channel).url,{waitUntil:'domcontentloaded',timeout:30000});}catch{}
   return list(org).find(x=>x.id===channel);
  })().finally(()=>opening.delete(k));opening.set(k,promise);return promise;
 }
 function session(org,channel){const s=sessions.get(key(org,channel));if(!s)throw new ProviderError('Abra a sessão em Contas conectadas e faça login.','blocked');return s;}
 async function observe(org,channel,{image=false,passive=false}={}){
  const s=session(org,channel);const pages=s.context.pages().filter(p=>validUrl(p.url(),channel));if(s.page.isClosed()&&pages.length)s.page=pages.at(-1);if(!validUrl(s.page.url(),channel))throw new ProviderError('A sessão está fora do canal permitido. Volte à página da conta.','blocked');
  const observation=await s.page.evaluate(({passive})=>{const visible=e=>{const r=e.getBoundingClientRect(),style=getComputedStyle(e);return r.width>0&&r.height>0&&style.visibility!=='hidden'&&style.display!=='none';};const body=document.body?.innerText||'';const auth=[...document.querySelectorAll('input[type=password],input[autocomplete=one-time-code],iframe[src*="captcha"]')].some(visible)||/scan (this |the )?qr|escaneie.*qr|enter.*verification code|insira.*código de verificação|confirme que você é humano|verify you are human/i.test(body);if(auth)return {challenge:true,text:'A sessão exige autenticação ou confirmação pelo usuário.',elements:[]};const elements=passive?[]:[...document.querySelectorAll('a,button,input,textarea,select,[role=button],[role=textbox],[contenteditable=true]')].filter(visible).slice(0,100).map((e,i)=>{const ref='e'+i;e.setAttribute('data-helpu-ref',ref);return {ref,role:e.getAttribute('role')||e.tagName.toLowerCase(),label:(e.getAttribute('aria-label')||e.getAttribute('placeholder')||e.innerText||e.getAttribute('name')||'').slice(0,160),type:e.getAttribute('type')||'',href:e.tagName==='A'?e.href:undefined};});return {challenge:false,text:body.slice(0,14000),elements};},{passive});
  s.challenge=observation.challenge;if(!passive){s.token=randomUUID();s.refs=new Set(observation.elements.map(e=>e.ref));s.lastObserved=Date.now();s.observedUrl=s.page.url();}if(observation.challenge)db.prepare('UPDATE browser_profiles SET confirmed_at=NULL,automation_allowed=0 WHERE org_id=? AND channel=?').run(org,channel);
  const profile=db.prepare('SELECT account_label,confirmed_at FROM browser_profiles WHERE org_id=? AND channel=?').get(org,channel);const result={...observation,accountDeclaredByUser:profile?.account_label||null,accountConfirmedByUserAt:profile?.confirmed_at||null,url:s.page.url(),title:await s.page.title(),snapshotToken:s.token,observedAt:s.lastObserved};if(image&&!observation.challenge)result.image=(await s.page.screenshot({type:'jpeg',quality:55,animations:'disabled'})).toString('base64');return result;
 }
 async function confirm(org,channel,accountLabel,automation,reviewed=false){localOnly();if(session(org,channel).owner)throw new ProviderError('Aguarde a execução atual antes de alterar a autorização.','blocked');const previous=db.prepare('SELECT uncertain_note FROM browser_profiles WHERE org_id=? AND channel=?').get(org,channel);if(previous?.uncertain_note&&!reviewed)throw new ProviderError('Confira o resultado da última ação na conta antes de liberar a sessão.','blocked');const label=String(accountLabel||'').trim().slice(0,120);if(!label)throw new ProviderError('Informe qual conta você abriu nesta sessão.','blocked');const observation=await observe(org,channel);if(observation.challenge)throw new ProviderError('Conclua o login no navegador antes de confirmar a conta.','blocked');db.prepare('UPDATE browser_profiles SET uncertain_note=NULL,pending_job_id=NULL,account_label=?,confirmed_at=?,automation_allowed=?,updated_at=? WHERE org_id=? AND channel=?').run(label,Date.now(),automation?1:0,Date.now(),org,channel);return list(org).find(x=>x.id===channel);}
 function claim(org,channel,runId){const s=session(org,channel);if(s.owner&&s.owner!==runId)throw new ProviderError('Esta conta está sendo usada por outra execução. Aguarde.','blocked');s.owner=runId;}
 function release(runId){for(const s of sessions.values())if(s.owner===runId)s.owner=null;}
 async function action(org,channel,input,runId){localOnly();const s=session(org,channel),p=db.prepare('SELECT * FROM browser_profiles WHERE org_id=? AND channel=?').get(org,channel);if(p?.uncertain_note)throw new ProviderError(p.uncertain_note,'blocked');if(!p?.confirmed_at||!p.automation_allowed)throw new ProviderError('Confirme a conta e permita a operação em Contas conectadas.','blocked');claim(org,channel,runId);
  if(s.challenge)throw new ProviderError('O usuário precisa concluir a autenticação.','blocked');if(!validUrl(s.page.url(),channel))throw new ProviderError('Página fora do canal permitido.','blocked');
  const apply=async operation=>{db.prepare('UPDATE browser_profiles SET pending_job_id=?,updated_at=? WHERE org_id=? AND channel=?').run(runId,Date.now(),org,channel);try{await operation();db.prepare('UPDATE browser_profiles SET pending_job_id=NULL WHERE org_id=? AND channel=?').run(org,channel);}catch(e){db.prepare('UPDATE browser_profiles SET automation_allowed=0,uncertain_note=? WHERE org_id=? AND channel=?').run('A interação não teve confirmação. Confira seu resultado antes de liberar a sessão.',org,channel);throw e;}};
  if(input.op==='navigate'){if(!validUrl(input.url,channel))throw new ProviderError('O destino não pertence a este canal.','blocked');await apply(()=>s.page.goto(input.url,{waitUntil:'domcontentloaded',timeout:30000}));}
  else if(input.op==='upload'&&s.chooser){const file=assetPath(org,input.assetId);await apply(()=>s.chooser.setFiles(file,{timeout:10000}));s.chooser=null;}
  else if(input.op==='scroll'){await apply(()=>s.page.mouse.wheel(0,Math.max(-1000,Math.min(1000,Number(input.amount)||600))));}
  else{if(s.observedUrl!==s.page.url()||input.snapshotToken!==s.token||Date.now()-s.lastObserved>90000||!s.refs.has(input.ref))throw new ProviderError('A página mudou. Observe novamente antes de agir.','blocked');const el=s.page.locator('[data-helpu-ref="'+input.ref+'"]');if(await el.count()!==1)throw new ProviderError('Elemento não encontrado. Observe novamente.','blocked');const secret=await el.evaluate(e=>e.type==='password'||e.autocomplete==='one-time-code'||/password|senha|token|otp|verification/i.test(e.name||''));if(secret)throw new ProviderError('Credenciais e códigos são preenchidos pelo usuário.','blocked');
   if(input.op==='click')await apply(()=>el.click({timeout:10000}));else if(input.op==='fill')await apply(()=>el.fill(String(input.text||'').slice(0,20000),{timeout:10000}));else if(input.op==='select')await apply(()=>el.selectOption(String(input.text||''),{timeout:10000}));else if(input.op==='press'){if(!['Enter','Tab','Escape','ArrowDown','ArrowUp','Backspace'].includes(input.text))throw new ProviderError('Tecla não permitida.','blocked');await apply(()=>el.press(input.text,{timeout:10000}));}else if(input.op==='upload'){const file=assetPath(org,input.assetId);await apply(()=>el.setInputFiles(file,{timeout:10000}));}else throw new ProviderError('Ação de navegador inválida.','blocked');}
  s.token=null;return {actionApplied:true,confirmation:'Interação aplicada. Observe o resultado; isto não confirma publicação ou envio.',url:s.page.url()};
 }
 async function close(org,channel){const s=sessions.get(key(org,channel));if(!s)return;if(s.owner)throw new ProviderError('Pause a conversa antes de fechar esta sessão.','blocked');await s.context.close();}
 return {list,open,observe,confirm,action,claim,release,close,freeze(org,channel,note){db.prepare('UPDATE browser_profiles SET uncertain_note=?,automation_allowed=0 WHERE org_id=? AND channel=?').run(note,org,channel);},async shutdown(){await Promise.allSettled([...sessions.values()].map(s=>s.context.close()));}};
}
