export const AGENTS=[
 {id:'director',name:'Diretor de marketing',short:'Direção',description:'Transforma objetivos em prioridades e coordena o plano de marketing.',task:'Faça um plano semanal fundamentado no negócio. Identifique lacunas de informação, prioridades e ações executáveis. Proponha até três peças de conteúdo alinhadas a uma única campanha.'},
 {id:'strategy',name:'Estrategista de marca',short:'Estratégia',description:'Organiza posicionamento, público, proposta de valor e argumentos.',task:'Analise posicionamento e proposta de valor. Diferencie fatos informados de hipóteses. Redija recomendações e perguntas essenciais; não invente produtos ou benefícios.'},
 {id:'creative',name:'Direção criativa',short:'Criação',description:'Cria conceitos, textos e briefings de imagens e vídeos.',task:'Produza até três peças de conteúdo coerentes entre si. Cada peça precisa de título, legenda, CTA, formato, canal e um briefing visual completo com a identidade da empresa. Se o pedido for vídeo, inclua roteiro de cenas na legenda.'},
 {id:'distribution',name:'Distribuição e presença',short:'Distribuição',description:'Organiza canais, frequência e oportunidades de publicação.',task:'Analise a presença digital com base apenas nas informações fornecidas. Proponha uma sequência de distribuição e melhorias de perfis, páginas e stories. Não alegue ter consultado sites ou contas.'},
 {id:'relationship',name:'Relacionamento',short:'Atendimento',description:'Prepara respostas com contexto e acompanha oportunidades.',task:'Prepare uma resposta objetiva à conversa fornecida. Use apenas fatos comerciais informados. Não invente preços, disponibilidade ou promessas. Se não houver contexto suficiente, peça informação ou encaminhe para a equipe. A resposta ao cliente deve ir em summary, sem saudação interna ou comentário de bastidor.'},
 {id:'analyst',name:'Analista de resultados',short:'Resultados',description:'Lê medições reais e recomenda os próximos testes.',task:'Analise somente as medições fornecidas. Não confunda ausência de dados com zero. Apresente observações, limitações de atribuição e próximos testes. Não prometa retorno.'}
];
export const CONNECTORS=[
 {id:'openai',name:'OpenAI',category:'Inteligência',icon:'ai',description:'Raciocínio e produção de texto para os agentes.',fields:[['apiKey','Chave da API',true],['model','Modelo das tarefas específicas',false,'gpt-5-mini'],['agentModel','Modelo da conversa e navegador',false,'gpt-6-astra']],docs:'https://platform.openai.com/api-keys'},
 {id:'higgsfield',name:'Higgsfield',category:'Criação',icon:'hf',description:'Geração de imagens e vídeos com acompanhamento de cada pedido.',fields:[['keyId','Identificador da chave',true],['keySecret','Segredo da chave',true],['imageModel','Modelo de imagem',false,'higgsfield-ai/soul/v2/standard'],['videoModel','Modelo de vídeo',false,'dop-turbo']],docs:'https://docs.higgsfield.ai/'},
 {id:'instagram',name:'Instagram',category:'Publicação',icon:'ig',description:'Feed, Reels e stories com confirmação da plataforma.',fields:[['accessToken','Token de acesso',true],['accountId','ID da conta profissional',false],['version','Versão da API Meta',false,'v24.0'],['appSecret','Segredo do aplicativo (webhooks)',true],['verifyToken','Token de verificação (webhooks)',true]],docs:'https://developers.facebook.com/docs/instagram-platform/'},
 {id:'whatsapp',name:'WhatsApp Business',category:'Relacionamento',icon:'wa',description:'Mensagens, modelos aprovados e recebimento por webhook.',fields:[['accessToken','Token de acesso',true],['phoneNumberId','ID do número de telefone',false],['version','Versão da API Meta',false,'v24.0'],['appSecret','Segredo do aplicativo (webhooks)',true],['verifyToken','Token de verificação (webhooks)',true]],docs:'https://developers.facebook.com/docs/whatsapp/cloud-api/'},
 {id:'google',name:'Perfil da Empresa no Google',category:'Presença',icon:'g',description:'Consulta do perfil e publicação de novidades em um perfil autorizado.',fields:[['accessToken','Token de acesso OAuth',true],['refreshToken','Refresh token OAuth',true],['clientId','Client ID OAuth',false],['clientSecret','Client secret OAuth',true],['accountId','ID da conta Google Business',false],['locationId','ID do local',false]],docs:'https://developers.google.com/my-business/'},
 {id:'metaAds',name:'Meta Ads',category:'Campanhas',icon:'ads',description:'Leitura de resultados e criação de campanhas pausadas para revisão.',fields:[['accessToken','Token de acesso',true],['adAccountId','ID da conta de anúncios',false],['version','Versão da API Meta',false,'v24.0']],docs:'https://developers.facebook.com/docs/marketing-api/'}
];
export const KINDS=['campaigns','content','leads','messages','tasks','metrics','pages','knowledge'];
export const DEFAULT_POLICY={enabled:false,autoMedia:false,allowPublishing:false,autoReply:false,dailyRuns:8,dailyMedia:3,dailyMessages:30,monthlyAdBudget:0,timeZone:'America/Sao_Paulo',publicBaseUrl:''};
export const CONTENT_FORMATS=['image','video','story','carousel','text'];
export const CHANNELS=['instagram','whatsapp','google','website','other'];
export const LEAD_STAGES=['new','qualified','proposal','won','lost'];
