import {randomUUID} from 'node:crypto';
import {COMMERCIAL_SECTORS,COMMERCIAL_INTERESTS,OFFER_FIELDS} from '../dist/assets/commercial-schema.js';
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const text=(v,max=4000)=>{if(typeof v!=='string')return '';const s=v.trim();if(s.length>max)fail('Texto acima do limite de '+max+' caracteres.');return s;};
const calendarDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
const decode=r=>r?{...JSON.parse(r.data),id:r.id,orgId:r.org_id,version:r.version}:null;
const email=v=>{const s=text(v,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))fail('Informe um e-mail válido.');return s;};
const https=v=>{let u;try{u=new URL(v);}catch{fail('Informe uma fonte HTTPS válida.');}if(u.protocol!=='https:'||u.username||u.password)fail('Informe uma fonte HTTPS válida.');return u.href;};

export function createCommercial({db,operator,now=Date.now,pricing}){
  const row=(id,kind)=>db.prepare('SELECT * FROM records WHERE id=? AND kind=?').get(id,kind);
  const all=async(kind,org)=> (await db.prepare('SELECT * FROM records WHERE kind=?'+(org?' AND org_id=?':'')+' ORDER BY updated_at DESC').all(kind,...(org?[org]:[]))).map(decode);
  const allowed=user=>{if(!operator(user))fail('Acesso restrito à equipe autorizada.',403);};
  const version=(r,input)=>{if(!Number.isInteger(input.version)||r?.version!==input.version)fail('Esta versão mudou. Atualize antes de continuar.',409);};
  async function transaction(fn){await db.exec('SAVEPOINT commercial_action');try{const out=await fn();await db.exec('RELEASE SAVEPOINT commercial_action');return out;}catch(e){await db.exec('ROLLBACK TO SAVEPOINT commercial_action');await db.exec('RELEASE SAVEPOINT commercial_action');throw e;}}
  async function write(org,id,kind,data,old,actor,action){const at=now(),event={id:randomUUID(),actor:String(actor),action,at};const next={...data,updatedAt:at,history:[...(old?JSON.parse(old.data).history||[]:[]),event]};delete next.id;delete next.orgId;delete next.version;
    if(old){if(!await db.prepare('UPDATE records SET data=?,updated_at=?,version=version+1 WHERE id=? AND version=? RETURNING id').get(JSON.stringify(next),at,id,old.version))fail('A versão mudou. Atualize a tela.',409);}
    else await db.prepare('INSERT INTO records(id,org_id,kind,data,external_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,org,kind,JSON.stringify(next),id,at,at);
    await db.prepare('INSERT INTO audit VALUES(?,?,?,?,?,?,?)').run(event.id,org,String(actor),'Comercial: '+action,id,'',at);return decode(await row(id,kind));
  }
  async function selectedMedia(org,input){if(!Array.isArray(input)||input.length>6)fail('Escolha até seis exemplos.');const result=[];for(const item of input){if(result.some(x=>x.id===item.id))fail('Escolha arquivos diferentes.');const a=await db.prepare('SELECT id,name,mime,size FROM assets WHERE id=? AND org_id=?').get(item.id,org);if(!a||!['image/png','image/jpeg','image/webp','video/mp4'].includes(a.mime))fail('Use imagens ou MP4 da empresa de origem.');if(a.size>3*1024*1024)fail('Use exemplos de até 3 MB para a apresentação.');const caption=text(item.caption,300),mode=item.mode;if(!caption||!['demonstration','real'].includes(mode))fail('Identifique cada exemplo como demonstração ou material real autorizado.');result.push({...a,caption,mode});}return result;}
  async function draft(org,input){const sector=text(input.sector,40);if(!Object.hasOwn(COMMERCIAL_SECTORS,sector))fail('Escolha um setor.');const result={sector,company:text(input.company,120),headline:text(input.headline,180),problem:text(input.problem,1500),application:text(input.application,1500),context:text(input.context,1500),source:text(input.source,1000),checkedAt:text(input.checkedAt,10),media:await selectedMedia(org,input.media||[])};
    if(!result.headline||!result.problem||!result.application)fail('Complete a mensagem, o problema e as aplicações.');if(result.context){result.source=https(result.source);if(!calendarDate(result.checkedAt)||result.checkedAt>new Date(now()).toISOString().slice(0,10))fail('Informe a data em que conferiu o contexto público.');}return result;}
  async function adminList(user){allowed(user);const pages=await all('commercial_page'),leads=await all('commercial_interest'),offers=await all('commercial_offer');return {pages,leads,offers,pricingSources:pricing?await pricing.proposalSources(user):[]};}
  async function pageAction(user,input){allowed(user);return transaction(async()=>{let old=input.id?await row(input.id,'commercial_page'):null,r=decode(old),id=r?.id,org=r?.orgId;
    if(!r){if(input.id||input.action!=='save')fail('Apresentação não encontrada.',404);org=text(input.orgId,100);if(!await db.prepare('SELECT role FROM memberships WHERE org_id=? AND user_id=?').get(org,user.id))fail('Escolha sua empresa de origem para criar a apresentação.',403);if(!/^[a-f\d-]{36}$/i.test(input.requestKey||''))fail('Identificador inválido.');id='commercial-page:'+org+':'+input.requestKey;old=await row(id,'commercial_page');if(old)return decode(old);r={slug:randomUUID(),published:null,createdAt:now(),history:[]};}
    else version(r,input);
    if(input.action==='save')r.draft=await draft(org,input);
    else if(input.action==='publish'){if(input.publicConsent!==true||input.materialConsent!==true)fail('Confira o conteúdo público e a autorização dos materiais antes de liberar o link.');r.published={...r.draft,number:(r.edition||0)+1,publishedAt:now()};r.edition=r.published.number;r.publicApproval={actor:String(user.id),at:now(),edition:r.edition};}
    else if(input.action==='unpublish')r.published=null;
    else fail('Ação inválida.');return write(org,id,'commercial_page',r,old,user.id,input.action);
  });}
  async function publicPage(slug){if(!/^[a-f\d-]{36}$/i.test(slug))fail('Apresentação indisponível.',404);const found=await db.prepare("SELECT * FROM records WHERE kind='commercial_page' AND json_extract(data,'$.slug')=?").get(slug),r=decode(found);if(!r?.published)fail('Apresentação indisponível.',404);return r;}
  function publicDTO(r){const p=r.published;return {slug:r.slug,sector:p.sector,company:p.company,headline:p.headline,problem:p.problem,application:p.application,context:p.context,source:p.source,checkedAt:p.checkedAt,edition:p.number,media:p.media.map((a,index)=>({mime:a.mime,caption:a.caption,mode:a.mode,url:'/api/presentations/'+r.slug+'/media/'+index}))};}
  async function publicMedia(slug,index){const r=await publicPage(slug);if(!/^\d$/.test(index))fail('Exemplo indisponível.',404);const a=r.published.media[Number(index)];if(!a)fail('Exemplo indisponível.',404);return {orgId:r.orgId,...a};}
  async function interest(slug,input){return transaction(async()=>{const r=await publicPage(slug);if(input.website)fail('Não foi possível receber a solicitação.');if(input.consent!==true)fail('Autorize o contato sobre esta solicitação.');const name=text(input.name,100),address=email(input.email),phone=text(input.phone,30),channel=input.channel,company=text(input.company,120),note=text(input.note,1500);if(!name||!company||!['email','whatsapp'].includes(channel))fail('Informe nome, empresa e canal de contato.');if(channel==='whatsapp'&&!/^\+?[\d ()-]{10,25}$/.test(phone))fail('Informe o WhatsApp com DDD.');const interests=input.interests;if(!Array.isArray(interests)||!interests.length||interests.length>4||interests.some(k=>!Object.hasOwn(COMMERCIAL_INTERESTS,k)))fail('Escolha pelo menos uma necessidade.');if(!/^[a-f\d-]{36}$/i.test(input.requestKey||''))fail('Identificador inválido.');
    const id='commercial-interest:'+r.slug+':'+input.requestKey;if(await row(id,'commercial_interest'))return {ok:true};
    const recent=await db.prepare("SELECT COUNT(*) AS total FROM records WHERE kind='commercial_interest' AND org_id=? AND json_extract(data,'$.email')=? AND created_at>?").get(r.orgId,address,now()-3600000);if(Number(recent.total)>=3)fail('Seu interesse já foi registrado. Aguarde o retorno da equipe.',429);
    await write(r.orgId,id,'commercial_interest',{pageId:r.id,pageEdition:r.published.number,company,name,email:address,phone:channel==='whatsapp'?phone:'',channel,interests:[...new Set(interests)],note,consent:{at:now(),version:'commercial-interest-2026-09-20',purpose:'return_requested_contact',channel},state:'new',createdAt:now()},null,'visitante','interest');return {ok:true};
  });}
  async function leadAction(user,input){allowed(user);return transaction(async()=>{const old=await row(input.id,'commercial_interest'),r=decode(old);if(!r)fail('Solicitação não encontrada.',404);version(r,input);if(!['new','contacted','proposal','closed','do_not_contact'].includes(input.state))fail('Etapa inválida.');if(r.state==='do_not_contact'&&input.state!=='do_not_contact')fail('Contato bloqueado. Uma nova autorização deve chegar em outra solicitação.',409);r.state=input.state;r.operatorNote=text(input.note,1500);r.assignee=String(user.id);return write(r.orgId,r.id,'commercial_interest',r,old,user.id,'interest_status');});}
  async function offerAction(user,input){allowed(user);return transaction(async()=>{let old=input.id?await row(input.id,'commercial_offer'):null,r=decode(old),org=r?.orgId,id=r?.id;
    if(!r){if(input.id||input.action!=='send')fail('Proposta não encontrada.',404);const lead=decode(await row(input.leadId,'commercial_interest'));if(!lead||lead.state==='do_not_contact')fail('Selecione uma solicitação de contato autorizada.');org=lead.orgId;if(!/^[a-f\d-]{36}$/i.test(input.requestKey||''))fail('Identificador inválido.');id='commercial-offer:'+org+':'+input.requestKey;old=await row(id,'commercial_offer');if(old)return decode(old);const recipient=await db.prepare('SELECT id,name,email FROM users WHERE lower(email)=?').get(email(input.recipientEmail));if(!recipient)fail('O destinatário precisa criar sua conta Helpu antes de receber a proposta privada.');r={recipientId:String(recipient.id),recipientName:recipient.name,recipientEmail:recipient.email,leadId:lead.id,company:lead.company,versions:[],history:[],createdAt:now()};}
    else version(r,input);
    if(r.state==='accepted')fail('Uma proposta aceita não pode ser alterada. Combine um novo escopo em outra proposta.',409);
    if(input.action==='send'){const contact=decode(await row(r.leadId,'commercial_interest'));if(!contact||contact.state==='do_not_contact')fail('Esta solicitação está bloqueada para contato.',409);const fields=Object.fromEntries(OFFER_FIELDS.map(([k])=>[k,text(input[k],5000)]));if(Object.values(fields).some(v=>!v))fail('Complete escopo, entregas, prazos, revisões, exclusões, pagamento e cancelamento.');if(!Number.isInteger(input.priceCents)||input.priceCents<1||input.priceCents>100000000)fail('Informe o valor total da proposta.');const validUntil=text(input.validUntil,10);if(!calendarDate(validUntil)||Date.parse(validUntil+'T23:59:59-03:00')<=now())fail('Escolha uma validade futura.');const title=text(input.title,150);if(!title)fail('Dê um título à proposta.');const pricingReference=input.pricingPlanId?(pricing?await pricing.proposalSource(user,input.pricingPlanId,input.pricingVersion):fail('A ficha de preço não está disponível.',409)):null;r.versions.push({...fields,pricingReference,title,priceCents:input.priceCents,validUntil,number:r.versions.length+1,at:now(),actor:String(user.id)});r.state='sent';r.acceptance=null;}
    else if(input.action==='withdraw'){r.state='withdrawn';r.withdrawalNote=text(input.note,1500);if(!r.withdrawalNote)fail('Informe por que a proposta foi retirada.');}
    else fail('Ação inválida.');return write(org,id,'commercial_offer',r,old,user.id,input.action);
  });}
  async function offers(user){return (await db.prepare("SELECT * FROM records WHERE kind='commercial_offer' AND json_extract(data,'$.recipientId')=? ORDER BY updated_at DESC").all(String(user.id))).map(decode);}
  async function customerAction(user,input){return transaction(async()=>{const old=await row(input.id,'commercial_offer'),r=decode(old);if(!r||r.recipientId!==String(user.id))fail('Proposta não encontrada.',404);version(r,input);if(r.state!=='sent')fail('Esta proposta não está disponível para aceite.',409);const p=r.versions.at(-1);if(Date.parse(p.validUntil+'T23:59:59-03:00')<=now())fail('Esta proposta venceu. Peça uma nova versão à equipe.',409);
    if(input.action==='accept'){if(input.consent!==true)fail('Confirme que leu e aceita esta versão.');r.state='accepted';r.acceptance={at:now(),actor:String(user.id),number:p.number};}
    else if(input.action==='changes'){r.customerNote=text(input.note,2000);if(!r.customerNote)fail('Descreva o ajuste que deseja.');r.state='changes_requested';}
    else fail('Ação inválida.');return write(r.orgId,r.id,'commercial_offer',r,old,user.id,input.action);
  });}
  async function preview(user,id){allowed(user);const r=decode(await row(id,'commercial_page'));if(!r)fail('Apresentação não encontrada.',404);const dto=publicDTO({...r,published:{...r.draft,number:0}});dto.media=r.draft.media.map(a=>({mime:a.mime,caption:a.caption,mode:a.mode,url:'/api/portal/files/'+a.id}));return dto;}
  async function canReadAsset(user,a){if(!operator(user))return false;return (await all('commercial_page',a.org_id)).some(r=>[...r.draft.media,...(r.published?.media||[])].some(m=>m.id===a.id));}
  return {adminList,pageAction,publicPage,publicDTO,publicMedia,interest,leadAction,offerAction,offers,customerAction,preview,canReadAsset};
}
