import {clientControl} from './admin-clients.mjs';
import {randomUUID,createHash} from 'node:crypto';
import {OFFERS,CONSULTING,OFFER_TERMS,PRODUCTION_MODES} from '../dist/assets/offer-catalog.js';
const fail=(message,status=409)=>{throw Object.assign(new Error(message),{status,state:'blocked'});};
const parse=r=>r?{...JSON.parse(r.data),id:r.id,orgId:r.org_id,version:r.version}:null;
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const hash=v=>createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
const money=v=>(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function createCommerce({db,operator,finance,creations,now=Date.now}){
 const read=async id=>parse(await db.prepare('SELECT * FROM records WHERE id=?').get(id));
 const rows=async(org,kind)=>(await db.prepare('SELECT * FROM records WHERE org_id=? AND kind=? ORDER BY created_at DESC').all(org,kind)).map(parse);
 async function put(org,kind,id,data,version){const {orgId,version:ignored,id:ignoredId,...clean}=data;if(version!==undefined){const r=await db.prepare('UPDATE records SET data=?,updated_at=?,version=version+1 WHERE id=? AND org_id=? AND version=? RETURNING id').get(JSON.stringify(clean),now(),id,org,version);if(!r)fail('Os dados mudaram. Atualize e tente novamente.');}else await db.prepare('INSERT INTO records(id,org_id,kind,data,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,org,kind,JSON.stringify(clean),now(),now());return read(id);}
 async function access(org,user,admin=false){await finance.access(org,user,admin);}
 const current=org=>read('subscription:'+org);
 async function reconcile(org){for(const u of await rows(org,'plan_usage')){if(u.state!=='reserved')continue;if(!u.jobId){const found=u.requestKey?await db.prepare('SELECT id FROM jobs WHERE org_id=? AND idempotency_key=?').get(org,u.requestKey):null;if(found){await put(org,'plan_usage',u.id,{...u,jobId:found.id},u.version);}else if(now()-u.createdAt>300000)await put(org,'plan_usage',u.id,{...u,state:'released'},u.version);continue;}let item;try{item=await creations.get(org,u.jobId);}catch{continue;}if(item.status==='complete'){
    const rootJob=await db.prepare('SELECT payload FROM jobs WHERE org_id=? AND id=?').get(org,u.jobId);
    if(JSON.parse(rootJob?.payload||'{}').approvalRequired){
      let approved=item.review==='approved';
      if(!u.revisionOf&&!approved)for(const revision of (await rows(org,'plan_usage')).filter(r=>r.revisionOf===u.id&&r.jobId)){const v=await creations.get(org,revision.jobId);if(v.status==='complete'&&v.review==='approved')approved=true;}
      if(!approved){if(!u.awaitingApproval)await put(org,'plan_usage',u.id,{...u,awaitingApproval:true},u.version);continue;}
    }
    await put(org,'plan_usage',u.id,{...u,state:'consumed',settledAt:now()},u.version);if(u.quoteId){const q=await read(u.quoteId);if(q?.state==='accepted')await put(org,'extra_quote',q.id,{...q,state:'delivered',deliveredAt:now()},q.version);}}
   else if(['failed','blocked'].includes(item.status)){const jobs=await db.prepare("SELECT state FROM jobs WHERE org_id=? AND (id=? OR json_extract(payload,'$.creationId')=?)").all(org,u.jobId,u.jobId);if(jobs.some(j=>['queued','working','waiting_provider','uncertain'].includes(j.state)))continue;await put(org,'plan_usage',u.id,{...u,state:'released',settledAt:now()},u.version);if(u.quoteId){const q=await read(u.quoteId);if(q?.state==='accepted')await put(org,'extra_quote',q.id,{...q,state:'void',reason:'Falha técnica: sem cobrança'},q.version);}}
  }}
 async function listing(org,user,admin=false){await access(org,user,admin);await reconcile(org);const subscription=await current(org),usage=await rows(org,'plan_usage'),quotes=await rows(org,'extra_quote'),plans=await rows(org,'monthly_plan');const control=await clientControl(db,org,now());const active=control.grantActive||subscription?.state==='active'&&subscription.start<=now()&&subscription.end>now();const used=type=>usage.filter(u=>u.period===subscription?.period&&u.type===type&&!u.quoteId&&!u.revisionOf&&u.state!=='released').length;return {assets:await db.prepare("SELECT id,name,mime FROM assets WHERE org_id=? AND (source_url IS NULL OR source_url NOT IN ('helpu:finance','helpu:review-preview')) AND (mime LIKE 'image/%' OR mime='video/mp4')" ).all(org),administrativeAccess:control.grantActive?{purpose:control.grant.purpose,end:control.grant.end,unlimited:true}:null,catalog:OFFERS,consulting:CONSULTING,terms:OFFER_TERMS,subscription,active,remaining:{image:Math.max(0,8-used('image')),video:Math.max(0,4-used('video'))},consumed:{image:usage.filter(u=>u.period===subscription?.period&&u.type==='image'&&!u.quoteId&&!u.revisionOf&&u.state==='consumed').length,video:usage.filter(u=>u.period===subscription?.period&&u.type==='video'&&!u.quoteId&&!u.revisionOf&&u.state==='consumed').length},reserved:{image:usage.filter(u=>u.period===subscription?.period&&u.type==='image'&&!u.quoteId&&!u.revisionOf&&u.state==='reserved').length,video:usage.filter(u=>u.period===subscription?.period&&u.type==='video'&&!u.quoteId&&!u.revisionOf&&u.state==='reserved').length},usage,quotes,plans,extrasCents:quotes.filter(q=>q.state==='delivered'&&!q.invoiceId).reduce((n,q)=>n+q.priceCents,0),clients:admin?await db.prepare('SELECT id,name FROM companies ORDER BY name').all():[]};}
 async function reserve(org,user,request,raw,key,approval){const control=await clientControl(db,org,now());if(control.state!=='active')fail('O acesso desta empresa está inativo. Entre em contato com a Helpu.');if(control.grantActive)return null;const s=await current(org);if(!s)return null;await access(org,{id:user});if(s.state!=='active'||s.start>now()||s.end<=now())fail('O período contratado não está ativo. Confira Meu plano.');await reconcile(org);
  const id='plan-use:'+hash([org,user,key]),old=await read(id);if(old){if(old.fingerprint!==hash(request))fail('Este pedido já corresponde a outra entrega.');if(old.state==='released')fail('A tentativa anterior falhou. Inicie um novo pedido.');return old;}
  await db.exec('SAVEPOINT plan_reserve');try{
   const live=await current(org);if(live.version!==s.version)fail('O plano mudou. Confira Meu plano.');await put(org,'subscription',s.id,s,s.version);
   const used=await rows(org,'plan_usage'),type=raw.adaptationOf?'adaptation':request.format==='reels'?'video':request.format==='carousel'?'carousel':'image';let revisionOf=null;
   if(request.revisionOf){const parent=used.find(u=>u.jobId===request.revisionOf);if(!parent||!['consumed','reserved'].includes(parent.state)||(await creations.get(org,parent.jobId)).status!=='complete')fail('A prévia anterior precisa estar concluída.');const prior=JSON.parse((await db.prepare('SELECT payload FROM jobs WHERE id=? AND org_id=?').get(parent.jobId,org)).payload).request;for(const field of ['prompt','format','duration','slideCount','attachments'])if(hash(prior[field])!==hash(request[field]))fail('A rodada de ajustes preserva o pedido e os materiais originais. Para outro conteúdo, inicie uma nova criação.');const root=parent.revisionOf||parent.id;if(used.some(u=>u.revisionOf===root&&u.state!=='released'))fail('A rodada de ajustes incluída já foi utilizada. Peça um orçamento à equipe para alterações adicionais.');revisionOf=root;}
   const available=type!=='adaptation'&&type!=='carousel'&&used.filter(u=>u.period===s.period&&u.type===type&&!u.quoteId&&!u.revisionOf&&u.state!=='released').length<(type==='video'?4:8);
   let quoteId=null;
   if(!revisionOf&&!available){if(type==='carousel'&&request.slideCount>5)fail('Carrosséis acima de cinco páginas precisam de orçamento individual.');
    const qid='extra:'+hash([org,user,key]);let q=await read(qid);
    if(type==='adaptation'&&(!q||q.type!=='adaptation'))fail('Solicite uma adaptação em Meu plano.');if(!q){q=await put(org,'extra_quote',qid,{state:'pending',userId:user,period:s.period,plan:s.plan,type,priceCents:OFFERS[s.plan].extras[type],fingerprint:hash(request),request:raw,description:request.prompt.slice(0,500),expiresAt:Math.min(s.end,now()+7*86400000),createdAt:now()});}
    if(q.fingerprint!==hash(request))fail('O pedido mudou. Solicite outro orçamento.');
    if(approval!==q.id||q.state!=='accepted'||String(q.acceptedBy)!==String(user)||q.expiresAt<now()){
     const extras=await rows(org,'extra_quote');const projectedCents=s.priceCents+q.priceCents+extras.filter(x=>x.id!==q.id&&['accepted','delivered'].includes(x.state)&&!x.invoiceId).reduce((n,x)=>n+x.priceCents,0);await db.exec('RELEASE SAVEPOINT plan_reserve');return {quote:{...q,projectedCents}};
    }quoteId=q.id;
   }
   const unit=await put(org,'plan_usage',id,{state:'reserved',period:s.period,type,fingerprint:hash(request),requestKey:key,quoteId,revisionOf,jobId:null,createdAt:now()});await db.exec('RELEASE SAVEPOINT plan_reserve');return unit;
  }catch(e){await db.exec('ROLLBACK TO SAVEPOINT plan_reserve');await db.exec('RELEASE SAVEPOINT plan_reserve');throw e;}
 }
 async function bind(unit,jobId){if(unit&&!unit.quote)await put(unit.orgId,'plan_usage',unit.id,{...unit,jobId},unit.version);}
 async function release(unit){if(unit&&!unit.quote){const live=await read(unit.id);if(live?.state==='reserved')await put(unit.orgId,'plan_usage',unit.id,{...live,state:'released'},live.version);if(unit.quoteId){const q=await read(unit.quoteId);if(q?.state==='accepted')await put(unit.orgId,'extra_quote',q.id,{...q,state:'void',reason:'Falha técnica: sem cobrança'},q.version);}}}
 async function guard(job){const control=await clientControl(db,job.org_id,now());if(control.state!=='active')fail('O acesso desta empresa está inativo.');if(control.grantActive)return;const s=await current(job.org_id);if(!s)return;const p=JSON.parse(job.payload||'{}'),root=job.kind==='creation'?job.id:p.creationId;if(!['creation','image','video'].includes(job.kind))return;if(!root)fail('Use Criar conteúdo ou peça ao Astra uma criação para contabilizar o plano.');const u=(await rows(job.org_id,'plan_usage')).find(u=>u.jobId===root);if(!u||u.state==='released')fail('Não há reserva válida para esta criação. Inicie um novo pedido em Meu plano.');}
 async function action(org,user,d,admin=false){await access(org,user,admin);let s=await current(org);
  if(d.action==='offer'){if(!admin)fail('Apenas a equipe pode oferecer o período.',403);if(!OFFERS[d.plan]||!Number.isFinite(Date.parse(d.start))||!Number.isFinite(Date.parse(d.end))||Date.parse(d.end)<=Date.parse(d.start)||Date.parse(d.end)-Date.parse(d.start)>32*86400000||!String(d.conditions||'').trim())fail('Informe plano, período de até 32 dias e condições comerciais.');if(s&&['active','offered','accepted'].includes(s.state)&&s.end>now())fail('Já existe um período em andamento.');const data={plan:d.plan,start:Date.parse(d.start),end:Date.parse(d.end),period:randomUUID(),state:'offered',mode:'demand',conditions:String(d.conditions).slice(0,4000),terms:OFFER_TERMS,priceCents:OFFERS[d.plan].priceCents,createdAt:now()};if(s)await put(org,'subscription_history',randomUUID(),s);return put(org,'subscription','subscription:'+org,data,s?.version);}
  if(d.action==='accept_plan'){if(admin||!s||s.state!=='offered'||d.version!==s.version||d.confirmed!==true)fail('Confira a proposta e aceite suas condições.');return put(org,'subscription',s.id,{...s,state:'accepted',acceptedBy:user.id,acceptedAt:now()},s.version);}
  if(d.action==='activate'){if(!admin||s?.state!=='accepted')fail('É necessário o aceite do cliente.',403);const payment=await finance.get(d.paymentId);if(!payment||payment.orgId!==org||payment.state!=='paid'||payment.amountCents<s.priceCents||payment.providerMode==='test')fail('Vincule uma cobrança paga desta empresa que cubra a mensalidade.');const previous=await rows(org,'subscription_history');if(previous.some(p=>p.paymentId===payment.id))fail('Este recebimento já foi utilizado em outro período.');return put(org,'subscription',s.id,{...s,state:'active',paymentId:payment.id,activatedAt:now()},s.version);}
  if(d.action==='mode'){if(!s||!PRODUCTION_MODES[d.mode])fail('Escolha o modo de produção.');return put(org,'subscription',s.id,{...s,mode:d.mode},s.version);}
  if(d.action==='adaptation'){if(admin||!s||s.state!=='active'||s.end<=now())fail('Solicite a adaptação pela conta do cliente com plano ativo.');const prior=await creations.get(org,d.creationId);if(prior.status!=='complete'||prior.review!=='approved'||!['feed','story'].includes(prior.format)||!['feed','story'].includes(d.format)||prior.format===d.format||prior.assets.length!==1)fail('Escolha uma imagem aprovada e outro formato (Feed ou Story).');const request={prompt:'Adapte exclusivamente o enquadramento desta arte aprovada para '+d.format+'. Preserve o conceito, textos, identidade e elementos. Não acrescente informações.',format:d.format,attachments:[prior.assets[0].id],requestId:randomUUID(),adaptationOf:prior.id};const qid='extra:'+hash([org,user.id,'creation:'+user.id+':'+request.requestId]);return put(org,'extra_quote',qid,{state:'pending',userId:user.id,period:s.period,plan:s.plan,type:'adaptation',priceCents:2900,fingerprint:hash({prompt:request.prompt,format:request.format,slideCount:1,duration:null,attachments:request.attachments}),request,description:'Adaptação de arte aprovada para '+d.format,expiresAt:Math.min(s.end,now()+7*86400000),createdAt:now()});}
  if(d.action==='accept_extra'){if(admin||d.confirmed!==true)fail('O cliente deve autorizar o preço.',403);const q=await read(d.id);if(!q||q.orgId!==org||String(q.userId)!==String(user.id)||!['pending','accepted'].includes(q.state)||q.expiresAt<now()||q.period!==s?.period||d.priceCents!==q.priceCents)fail('O orçamento mudou ou expirou. Confira Meu plano.');if(q.state==='pending')await put(org,'extra_quote',q.id,{...q,state:'accepted',acceptedBy:user.id,acceptedAt:now()},q.version);return creations.submit(org,user.id,q.request,{commercialApproval:q.id});}
  if(d.action==='decline_extra'){const q=await read(d.id);if(admin||!q||q.orgId!==org||String(q.userId)!==String(user.id)||q.state!=='pending')fail('Orçamento indisponível.');return put(org,'extra_quote',q.id,{...q,state:'declined'},q.version);}
  if(d.action==='invoice_extras'){if(!admin)fail('Acesso restrito à equipe.',403);await reconcile(org);const extras=(await rows(org,'extra_quote')).filter(q=>q.state==='delivered'&&!q.invoiceId);if(!extras.length)fail('Não há extras entregues para faturar.');await db.exec('SAVEPOINT invoice_extras');try{const charge=await finance.action(org,user,{action:'create',requestKey:hash(extras.map(q=>q.id).sort()).slice(0,8)+'-'+hash(extras.map(q=>q.id).sort()).slice(8,12)+'-'+hash(extras.map(q=>q.id).sort()).slice(12,16)+'-'+hash(extras.map(q=>q.id).sort()).slice(16,20)+'-'+hash(extras.map(q=>q.id).sort()).slice(20,32),description:d.includeMonthly?'Mensalidade + extras autorizados e entregues':'Extras autorizados e entregues',reference:'Extras: '+extras.map(q=>q.id.slice(-8)).join(', '),competence:d.competence,dueDate:d.dueDate,amountCents:extras.reduce((n,q)=>n+q.priceCents,0)+(d.includeMonthly?s.priceCents:0),terms:'Itens extras autorizados individualmente e entregues. '+extras.map(q=>q.description+' — '+money(q.priceCents)).join('\n')},true);for(const q of extras)await put(org,'extra_quote',q.id,{...q,invoiceId:charge.id},q.version);await db.exec('RELEASE SAVEPOINT invoice_extras');return charge;}catch(e){await db.exec('ROLLBACK TO SAVEPOINT invoice_extras');await db.exec('RELEASE SAVEPOINT invoice_extras');throw e;}}
  if(d.action==='save_plan'){if(!s||s.state!=='active')fail('Ative um plano antes de planejar.');if(!Array.isArray(d.items)||!d.items.length||d.items.length>12)fail('Planeje até 12 conteúdos.');const items=d.items.map((x,i)=>{if(!['feed','story','reels'].includes(x.format)||!String(x.prompt||'').trim()||!Number.isFinite(Date.parse(x.publishAt))||Date.parse(x.publishAt)<s.start||Date.parse(x.publishAt)>=s.end)fail('Informe formato, briefing e data dentro do período.');return {id:randomUUID(),format:x.format,prompt:String(x.prompt).slice(0,4000),publishAt:new Date(x.publishAt).toISOString(),attachments:Array.isArray(x.attachments)?x.attachments:[],duration:x.duration===30?30:15};});if(items.filter(x=>x.format==='reels').length>4||items.filter(x=>x.format!=='reels').length>8)fail('O planejamento comporta oito imagens e quatro vídeos.');return put(org,'monthly_plan',randomUUID(),{period:s.period,state:'review',items,createdBy:user.id,createdAt:now()});}
  if(d.action==='approve_plan'||d.action==='produce_plan'){const p=await read(d.id);if(!p||p.orgId!==org||p.period!==s?.period)fail('Planejamento indisponível.');if(d.action==='approve_plan'){if(admin||p.state!=='review'||d.confirmed!==true)fail('O cliente precisa aprovar o planejamento.');return put(org,'monthly_plan',p.id,{...p,state:'approved',approvedBy:user.id,approvedAt:now()},p.version);}if(!['approved','producing'].includes(p.state))fail('Aprove o planejamento antes de produzir.');const owner={id:p.approvedBy};await access(org,owner);const items=[];for(const item of p.items){if(item.creationId){items.push(item);continue;}try{const c=await creations.submit(org,owner.id,{...item,requestId:'monthly_'+p.id+'_'+item.id},{publicationAt:item.publishAt});items.push({...item,creationId:c.id,error:null});}catch(e){items.push({...item,error:e.message});}}return put(org,'monthly_plan',p.id,{...p,state:'producing',items},p.version);}
  fail('Ação não reconhecida.');
 }
 async function chat(org,user,input){const match=/^CONFIRMAR EXTRA ([a-f0-9]{64})$/i.exec(input.trim());if(!match)return null;const q=await read('extra:'+match[1]);if(!q||q.orgId!==org)fail('Orçamento não encontrado.');const result=await action(org,user,{action:'accept_extra',id:q.id,priceCents:q.priceCents,confirmed:true});return 'Extra autorizado por '+money(q.priceCents)+'. Pedido encaminhado para produção. Cobrança somente após aprovação da entrega. Criação: '+result.id+'.';}
 return {current,listing,reserve,bind,release,guard,action,reconcile,chat};
}
