import {randomUUID} from 'node:crypto';
const fail=(m,status=400)=>{throw Object.assign(new Error(m),{status});};
const text=(v,n=300)=>String(v??'').trim().slice(0,n);
const date=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'')&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const read=r=>r?{...JSON.parse(r.data),id:r.id,orgId:r.org_id,version:r.version}:null;
export const financeToday=now=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
export function financeState(r,now=Date.now()){return r.state==='open'&&r.dueDate<financeToday(now)?'overdue':r.state;}
export function reminderStage(r,now){if(r.state!=='open'||!r.instrument)return null;const days=Math.round((Date.parse(r.dueDate+'T12:00:00Z')-Date.parse(financeToday(now)+'T12:00:00Z'))/86400000);return days===2?'due_2':days<2&&r.instrument.createdAt>=Date.parse(r.dueDate+'T00:00:00-03:00')-2*86400000?'available':null;}
export function createFinance({db,operator,storeAsset,now=Date.now,deliver}){
 async function access(org,user,admin=false){if(admin){if(!operator(user))fail('Acesso restrito à equipe Helpu.',403);}else{const m=await db.prepare('SELECT role FROM memberships WHERE org_id=? AND user_id=?').get(org,user.id);if(!m||!['owner','admin'].includes(m.role))fail('O financeiro é restrito aos responsáveis da empresa.',403);}if(!await db.prepare('SELECT id FROM companies WHERE id=?').get(org))fail('Empresa não encontrada.',404);}
 const get=async id=>read(await db.prepare("SELECT * FROM records WHERE id=? AND kind='finance_receivable'").get(id));
 async function update(r,user,event,detail){const version=r.version;r.history.push({event,detail,at:now(),actor:user.id});const {id,orgId,...data}=r;delete data.version;const changed=await db.prepare('UPDATE records SET data=?,version=version+1,updated_at=? WHERE id=? AND version=? RETURNING id').get(JSON.stringify(data),now(),id,version);if(!changed)fail('A cobrança mudou. Atualize antes de continuar.',409);return get(id);}
 async function listing(org,user,admin=false){if(admin){if(!operator(user))fail('Acesso restrito à equipe Helpu.',403);}else await access(org,user);const rows=await db.prepare("SELECT * FROM records WHERE kind='finance_receivable'"+(admin?'':' AND org_id=?')+' ORDER BY created_at DESC').all(...admin?[]:[org]);const clients=admin?await db.prepare('SELECT id,name FROM companies ORDER BY name').all():[];const preferences=org?read(await db.prepare("SELECT * FROM records WHERE id=? AND kind='finance_preferences'").get('finance-pref:'+org+':'+user.id)):null;return {receivables:rows.map(read).filter(r=>admin||r.providerMode!=='test').map(r=>({...r,displayState:financeState(r,now())})),clients,reminders:admin?(await db.prepare("SELECT data,created_at FROM records WHERE kind='finance_reminder' ORDER BY created_at DESC" ).all()).map(row=>({...JSON.parse(row.data),createdAt:row.created_at})):[],remindersEnabled:!!preferences?.enabled};}
 async function action(org,user,d,admin=false){await access(org,user,admin);
  if(d.action==='preferences'&&!admin){const id='finance-pref:'+org+':'+user.id;await db.prepare('INSERT INTO records(id,org_id,kind,data,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').run(id,org,'finance_preferences',JSON.stringify({userId:user.id,enabled:d.enabled===true,at:now()}),now(),now());return {enabled:d.enabled===true};}
  if(!admin)fail('Ação restrita à equipe Helpu.',403);
  if(d.action==='create'){
   if(!/^[a-f\d-]{36}$/.test(d.requestKey||''))fail('Identificador do pedido inválido.');
   const description=text(d.description),terms=text(d.terms,2000),reference=text(d.reference),competence=text(d.competence,7);
   if(!description||!terms||!reference||!/^\d{4}-(0[1-9]|1[0-2])$/.test(competence)||!date(d.dueDate)||!Number.isSafeInteger(d.amountCents)||d.amountCents<1||d.amountCents>100000000)fail('Informe descrição, referência do pedido, competência, valor, vencimento e condições acordadas.');
   const id='fin:'+d.requestKey,data={description,terms,reference,competence,amountCents:d.amountCents,dueDate:d.dueDate,origin:'sicredi_manual',state:'open',instrument:null,instruments:[],proofs:[],payments:[],history:[{event:'created',at:now(),actor:user.id}],createdAt:now()};
   const previous=await get(id);if(previous){if(previous.orgId!==org||['description','terms','reference','competence','amountCents','dueDate'].some(k=>previous[k]!==data[k]))fail('Este identificador corresponde a outra cobrança.',409);return previous;}
   await db.prepare('INSERT INTO records(id,org_id,kind,data,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,org,'finance_receivable',JSON.stringify(data),now(),now());return get(id);
  }
  const r=await get(d.id);if(!r||r.orgId!==org)fail('Cobrança não encontrada.',404);if(r.version!==d.version)fail('A cobrança mudou. Atualize antes de continuar.',409);
  if(r.origin!=='sicredi_manual')fail('Gerencie este pagamento no provedor de origem.',409);
  const note=text(d.note,1000);if(!note)fail('Registre a justificativa ou referência da conferência.');
  if(d.action==='amend'){if(r.state!=='open'||r.instrument)fail('Retire o boleto ativo pelo fluxo de reemissão antes de corrigir a cobrança.',409);if(!text(d.description)||!text(d.terms)||!Number.isSafeInteger(d.amountCents)||d.amountCents<1||d.amountCents>100000000||!date(d.dueDate))fail('Confira descrição, valor, vencimento e condições.');r.history.push({event:'before_amend',at:now(),actor:user.id,detail:JSON.stringify({description:r.description,amountCents:r.amountCents,dueDate:r.dueDate,terms:r.terms})});Object.assign(r,{description:text(d.description),terms:text(d.terms,2000),amountCents:d.amountCents,dueDate:d.dueDate});}
  else if(d.action==='paid'){if(!['open','pending'].includes(r.state))fail('Esta cobrança não está em aberto.',409);if(d.amountCents!==r.amountCents||!date(d.paidDate)||d.paidDate>financeToday(now()))fail('Confira o valor integral e a data do recebimento. Pagamento parcial exige conciliação fora deste fluxo.');if(d.bankConfirmed!==true)fail('Confirme o recebimento no banco. Comprovante não confirma liquidação.');r.state='paid';r.payments.push({id:randomUUID(),amountCents:d.amountCents,date:d.paidDate,reference:note,actor:user.id,at:now(),source:'bank_manual'});}
  else if(d.action==='reject_proof'){if(r.state!=='pending')fail('Não há comprovante aguardando conferência.',409);r.state='open';}
  else if(d.action==='cancel_request'){if(!['open','pending'].includes(r.state))fail('Esta cobrança não pode ser cancelada.',409);r.state='cancel_pending';}
  else if(d.action==='cancel_confirm'){if(r.state!=='cancel_pending'||d.bankConfirmed!==true)fail('Confirme o cancelamento no banco antes de encerrar.',409);r.state='canceled';}
  else if(d.action==='reissue'){if(r.state!=='open'||!r.instrument||d.bankConfirmed!==true||!date(d.dueDate))fail('Confirme a baixa do boleto anterior no banco e o novo vencimento.',409);r.instruments.push({...r.instrument,state:'replaced',replacedAt:now(),reason:note});r.instrument=null;r.dueDate=d.dueDate;}
  else fail('Ação inválida.');return update(r,user,d.action,note);
 }
 async function upload(org,user,d,name,bytes,admin=false){await access(org,user,admin);const r=await get(d.id);if(!r||r.orgId!==org)fail('Cobrança não encontrada.',404);if(r.version!==d.version)fail('A cobrança mudou. Atualize.',409);if(bytes.length>3*1024*1024||bytes.length<8||!bytes.subarray(0,5).equals(Buffer.from('%PDF-')))fail('Envie um PDF de até 3 MB.');
  if(admin){if(r.state!=='open'||r.instrument)fail('Reemita o boleto antes de substituir seu arquivo.',409);if(!/^\d{47,48}$/.test(d.code||'')||!text(d.bankReference))fail('Informe a linha digitável sem espaços e a referência do boleto no banco.');}
  else if(!['open','pending'].includes(r.state)||r.proofs.length>=10)fail('Esta cobrança não aceita outro comprovante.',409);
  const asset=await storeAsset(org,text(name,120)||'documento.pdf',bytes,'helpu:finance');
  if(admin)r.instrument={id:randomUUID(),asset,code:d.code,bankReference:text(d.bankReference),createdAt:now(),state:'active'};
  else{r.proofs.push({asset,at:now(),actor:user.id});r.state='pending';}
  return update(r,user,admin?'boleto_attached':'proof_received',asset.id);
 }
 async function authorizeFile(user,asset){if(asset.source_url!=='helpu:finance')return false;if(operator(user))return true;await access(asset.org_id,user);const rows=await db.prepare("SELECT * FROM records WHERE org_id=? AND kind='finance_receivable'").all(asset.org_id);if(!rows.map(read).some(r=>r.instrument?.asset.id===asset.id||r.proofs.some(p=>p.asset.id===asset.id)))fail('Documento substituído ou indisponível.',404);return true;}
 async function tick(){if(!deliver)return;let dispatched=0;const rows=await db.prepare("SELECT * FROM records WHERE kind='finance_receivable'").all();for(const row of rows){const r=read(row),stage=reminderStage(r,now());if(!stage)continue;const prefs=await db.prepare("SELECT * FROM records WHERE org_id=? AND kind='finance_preferences'").all(r.orgId);for(const pref of prefs){const p=read(pref);if(!p.enabled)continue;try{await access(r.orgId,{id:p.userId});}catch{continue;}const id='fin-rem:'+r.id+':'+r.instrument.id+':'+stage+':'+p.userId;if(await db.prepare('SELECT id FROM records WHERE id=?').get(id))continue;
    const available=await deliver(r.orgId,p.userId,stage,true);if(!available)continue;
    const live=await get(r.id),consent=read(await db.prepare('SELECT * FROM records WHERE id=?').get(pref.id));if(!consent?.enabled||live.version!==r.version||live.state!=='open')continue;
    const claim=await db.prepare('INSERT INTO records(id,org_id,kind,data,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING RETURNING id').get(id,r.orgId,'finance_reminder',JSON.stringify({state:'sending',stage,receivable:r.id,userId:p.userId}),now(),now());if(!claim)continue;
    let state;try{state=await deliver(r.orgId,p.userId,stage,false)||'skipped';}catch{state='uncertain';}await db.prepare('UPDATE records SET data=?,updated_at=? WHERE id=?').run(JSON.stringify({state,stage,receivable:r.id,userId:p.userId}),now(),id);if(++dispatched>=3)return;
   }}
 }
 async function chat(org,user,input){
  const normalized=input.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  if(!/^(?:(?:quero|preciso|mostre|mostrar|ver|consultar|envie|enviar|mande|buscar|qual|quais|onde|como|esta|meu|minha|meus|minhas|o|a|os|as|status|do|da|dos|das|de|um|uma|segunda|via|por|favor|estao|pagar|pago|pagas|pagos|pendentes|vencidas|financeiro|boleto|boletos|cobranca|cobrancas|pagamento|pagamentos|fatura|faturas)\s*)+[?.!]*$/.test(normalized)||!/(boleto|financeiro|cobranca|pagamento|fatura)/.test(normalized))return null;
  let result;try{result=await listing(org,user);}catch(e){if(e.status===403)return 'O financeiro é restrito aos responsáveis da empresa. Peça ao proprietário para consultar Minha empresa → Financeiro.';throw e;}
  const labels={open:'em aberto',overdue:'vencida',pending:'aguardando confirmação',paid:'paga',cancel_pending:'cancelamento em conferência',canceled:'cancelada'};
  return (result.receivables.length?result.receivables.slice(0,10).map(r=>`${r.description}: ${(r.amountCents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}, vencimento ${r.dueDate.split('-').reverse().join('/')}, ${labels[r.displayState]}.`).join('\n'):'Não há cobranças registradas para sua empresa.')+'\n\nAbra Minha empresa → Financeiro na Helpu para baixar o boleto atual, copiar a linha digitável ou enviar um comprovante. O envio do comprovante não confirma o pagamento.';
 }
 async function recordStripe(p){if(!p)return {received:true,ignored:true};const id='fin-stripe:'+p.mode+':'+p.objectId;const data={description:p.description,reference:p.reference,competence:financeToday(p.periodAt||p.paidAt).slice(0,7),dueDate:financeToday(p.dueAt||p.paidAt),amountCents:p.amountCents,origin:'stripe',providerMode:p.mode,state:'paid',terms:'Pagamento confirmado no Stripe. Condições conforme contratação no provedor. Este registro não é uma nota fiscal.',instrument:null,instruments:[],proofs:[],payments:[{id:p.objectId,amountCents:p.amountCents,date:financeToday(p.paidAt),reference:p.eventId,source:'stripe_verified',at:p.paidAt}],history:[{event:'paid',actor:'stripe',at:now(),detail:'Confirmação autenticada: '+p.eventId}],createdAt:now()};const inserted=await db.prepare('INSERT INTO records(id,org_id,kind,data,external_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING RETURNING id').get(id,p.orgId,'finance_receivable',JSON.stringify(data),id,now(),now());return {received:true,replayed:!inserted};}
 return {listing,action,upload,authorizeFile,tick,access,get,chat,recordStripe};
}
