-- Preserve the existing Operating Kernel data model. No workers are started.
-- This schema is deliberately absent from the public Data API schemas.
CREATE SCHEMA helpu;
REVOKE ALL ON SCHEMA helpu FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA helpu TO service_role;

CREATE TABLE helpu.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL, email text NOT NULL, company text NOT NULL DEFAULT '',
  salt text NOT NULL, password_hash text NOT NULL, created_at bigint NOT NULL
);
CREATE UNIQUE INDEX users_email ON helpu.users (lower(email));
CREATE TABLE helpu.sessions (
  token_hash text PRIMARY KEY, user_id bigint NOT NULL REFERENCES helpu.users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL
);
CREATE TABLE helpu.portal_migrations (version integer PRIMARY KEY, applied_at bigint NOT NULL);
CREATE TABLE helpu.companies (
  id text PRIMARY KEY, name text NOT NULL, profile text NOT NULL DEFAULT '{}',
  policy text NOT NULL DEFAULT '{}', created_at bigint NOT NULL, updated_at bigint NOT NULL
);
CREATE TABLE helpu.memberships (
  org_id text NOT NULL REFERENCES helpu.companies(id), user_id bigint NOT NULL REFERENCES helpu.users(id),
  role text NOT NULL DEFAULT 'owner', PRIMARY KEY(org_id,user_id)
);
CREATE INDEX idx_memberships_user ON helpu.memberships(user_id);
CREATE TABLE helpu.records (
  id text PRIMARY KEY, org_id text NOT NULL REFERENCES helpu.companies(id), kind text NOT NULL,
  data text NOT NULL, external_id text, created_at bigint NOT NULL, updated_at bigint NOT NULL,
  version integer NOT NULL DEFAULT 1, UNIQUE(org_id,kind,external_id)
);
CREATE INDEX idx_records_org_kind ON helpu.records(org_id,kind,created_at);
CREATE INDEX records_operation ON helpu.records(org_id,(data::jsonb->>'operationId'));
CREATE INDEX operations_thread ON helpu.records(org_id,(data::jsonb->>'threadId')) WHERE kind='operations';
CREATE TABLE helpu.integrations (
  org_id text NOT NULL REFERENCES helpu.companies(id), provider text NOT NULL, sealed text NOT NULL,
  verified_at bigint, error text, updated_at bigint NOT NULL, PRIMARY KEY(org_id,provider)
);
COMMENT ON COLUMN helpu.integrations.sealed IS 'Existing AES-GCM ciphertext. The local encryption key is not transferred by the data import.';
CREATE TABLE helpu.assets (
  id text PRIMARY KEY, org_id text NOT NULL REFERENCES helpu.companies(id), name text NOT NULL,
  mime text NOT NULL, size bigint NOT NULL, path text NOT NULL, source_url text, created_at bigint NOT NULL,
  storage_bucket text, storage_path text, sha256 text, storage_verified_at timestamptz,
  CHECK (sha256 IS NULL OR sha256 ~ '^[a-f0-9]{64}$'), UNIQUE(storage_bucket,storage_path)
);
CREATE INDEX idx_assets_org ON helpu.assets(org_id,created_at);
CREATE TABLE helpu.jobs (
  id text PRIMARY KEY, org_id text NOT NULL REFERENCES helpu.companies(id), user_id bigint REFERENCES helpu.users(id),
  kind text NOT NULL, payload text NOT NULL, state text NOT NULL DEFAULT 'queued', scheduled_at bigint NOT NULL,
  attempts integer NOT NULL DEFAULT 0, lease_until bigint, external text, output text, error text,
  idempotency_key text NOT NULL, created_at bigint NOT NULL, updated_at bigint NOT NULL,
  cancel_requested integer NOT NULL DEFAULT 0, UNIQUE(org_id,idempotency_key)
);
CREATE INDEX idx_jobs_due ON helpu.jobs(state,scheduled_at);
CREATE INDEX idx_jobs_org ON helpu.jobs(org_id,created_at);
CREATE INDEX jobs_operation ON helpu.jobs(org_id,(payload::jsonb->>'operationId'));
CREATE UNIQUE INDEX jobs_content_active ON helpu.jobs(org_id,(payload::jsonb->>'contentId'))
  WHERE kind IN ('image','video','publish') AND state IN ('queued','working','waiting_provider','uncertain');
CREATE UNIQUE INDEX jobs_message_active ON helpu.jobs(org_id,(payload::jsonb->>'messageId'))
  WHERE kind='send' AND state IN ('queued','working','waiting_provider','uncertain');
CREATE UNIQUE INDEX jobs_campaign_active ON helpu.jobs(org_id,(payload::jsonb->>'campaignId'))
  WHERE kind='metaCampaign' AND state IN ('queued','working','waiting_provider','uncertain');
CREATE UNIQUE INDEX conversation_active ON helpu.jobs(org_id,(payload::jsonb->>'conversationId'))
  WHERE kind='conversation' AND state IN ('queued','working');
CREATE TABLE helpu.audit (
  id text PRIMARY KEY, org_id text NOT NULL, actor text NOT NULL, action text NOT NULL,
  resource_id text, note text NOT NULL DEFAULT '', created_at bigint NOT NULL
);
CREATE INDEX idx_audit_org ON helpu.audit(org_id,created_at);
CREATE TABLE helpu.usage_reservations (
  job_id text PRIMARY KEY REFERENCES helpu.jobs(id), org_id text NOT NULL REFERENCES helpu.companies(id),
  category text NOT NULL, day text NOT NULL, created_at bigint NOT NULL
);
CREATE INDEX usage_org_day ON helpu.usage_reservations(org_id,category,day);
CREATE TABLE helpu.conversations (
  id text PRIMARY KEY, org_id text NOT NULL REFERENCES helpu.companies(id), title text NOT NULL,
  created_at bigint NOT NULL, updated_at bigint NOT NULL
);
CREATE INDEX conversations_org ON helpu.conversations(org_id,updated_at);
CREATE TABLE helpu.conversation_messages (
  id text PRIMARY KEY, conversation_id text NOT NULL REFERENCES helpu.conversations(id),
  org_id text NOT NULL REFERENCES helpu.companies(id), role text NOT NULL, text text NOT NULL,
  attachments text NOT NULL DEFAULT '[]', job_id text, created_at bigint NOT NULL
);
CREATE INDEX conversation_messages_thread ON helpu.conversation_messages(org_id,conversation_id,created_at);
CREATE TABLE helpu.conversation_events (
  id text PRIMARY KEY, org_id text NOT NULL, conversation_id text NOT NULL, job_id text NOT NULL,
  kind text NOT NULL, label text NOT NULL, detail text, created_at bigint NOT NULL
);
CREATE INDEX conversation_events_job ON helpu.conversation_events(org_id,job_id,created_at);
CREATE INDEX events_operation ON helpu.conversation_events(org_id,(detail::jsonb->>'operationId'),created_at);
CREATE TABLE helpu.browser_profiles (
  org_id text NOT NULL REFERENCES helpu.companies(id), channel text NOT NULL, account_label text NOT NULL DEFAULT '',
  confirmed_at bigint, automation_allowed integer NOT NULL DEFAULT 0, updated_at bigint NOT NULL,
  uncertain_note text, pending_job_id text, PRIMARY KEY(org_id,channel)
);
CREATE TABLE helpu.cloud_imports (
  snapshot_hash text PRIMARY KEY CHECK(snapshot_hash ~ '^[a-f0-9]{64}$'), manifest jsonb NOT NULL,
  imported_at timestamptz NOT NULL DEFAULT now(), files_verified_at timestamptz
);

DO $security$
DECLARE item record;
BEGIN
  FOR item IN SELECT tablename FROM pg_tables WHERE schemaname='helpu' LOOP
    EXECUTE format('ALTER TABLE helpu.%I ENABLE ROW LEVEL SECURITY',item.tablename);
    EXECUTE format('ALTER TABLE helpu.%I FORCE ROW LEVEL SECURITY',item.tablename);
  END LOOP;
END $security$;
REVOKE ALL ON ALL TABLES IN SCHEMA helpu FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA helpu FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA helpu TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA helpu TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA helpu REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA helpu REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;

INSERT INTO storage.buckets(id,name,public,file_size_limit)
  VALUES('helpu-private','helpu-private',false,52428800);
-- No public or authenticated storage policy is added. Access requires a trusted server.
